// Regenerates server/bank.mjs so every file in server/questions is bundled.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const dir = path.dirname(fileURLToPath(import.meta.url));
const files = fs.readdirSync(path.join(dir, 'questions')).filter(f => f.endsWith('.js')).sort();
const src = [
  '// generated by build-bank.mjs — do not edit',
  "import './core.js';",
  "import './wordlist.js';",
  ...files.map(f => `import './questions/${f}';`),
  '',
].join('\n');
fs.writeFileSync(path.join(dir, 'bank.mjs'), src);
console.log(`bank.mjs: ${files.length} files`);
