(function () {
  const q = Trench.q;
  Trench.add('Business',

q('Name a bank or investment bank',
  'JPMorgan/JPMorgan Chase/Chase/JP Morgan; Bank of America/BofA; Wells Fargo; Goldman Sachs/Goldman; Citi/Citibank/Citigroup; Morgan Stanley',
  '',
  'Capital One; TD Bank/TD; PNC; US Bank/U.S. Bank; Truist; Barclays; HSBC; Deutsche Bank; UBS; Credit Suisse; BNP Paribas; Santander; Ally; Charles Schwab/Schwab; Fidelity; American Express/Amex; Discover; Citizens; KeyBank; Fifth Third; Regions; M&T; Huntington; BMO; RBC/Royal Bank of Canada; Scotiabank; Lazard; Evercore; Jefferies; Lehman Brothers/Lehman; Bear Stearns; Merrill Lynch/Merrill; Silicon Valley Bank/SVB; First Republic; Silvergate; Signature Bank; Washington Mutual/WaMu; Wachovia; Countrywide; Bank of New York Mellon/BNY Mellon/BNY; State Street; Northern Trust; Raymond James; Edward Jones; Stifel; Piper Sandler; Houlihan Lokey; Moelis; PJT Partners/PJT; Centerview; Guggenheim; Perella Weinberg; Qatalyst; Rothschild; Nomura; Mizuho; MUFG/Mitsubishi UFJ; SMBC/Sumitomo Mitsui; Macquarie; RBC Capital Markets; Wells Fargo Securities; Truist Securities; William Blair; Cowen; Baird; Lincoln International; Harris Williams; Greenhill; LionTree; Allen and Company/Allen & Co',
  'Societe Generale; Natixis; Credit Agricole; ING; ABN AMRO; Rabobank; Commerzbank; UniCredit; Intesa Sanpaolo; BBVA; CaixaBank; Lloyds; NatWest; Standard Chartered; Nordea; Danske Bank; SEB; Handelsbanken; DNB; KBC; Erste; Raiffeisen; Bank of China; ICBC; China Construction Bank; Agricultural Bank of China; HDFC; ICICI; State Bank of India/SBI; Kotak; Itau; Bradesco; Banco do Brasil; Banorte; DBS; OCBC; UOB; Maybank; Commonwealth Bank; Westpac; ANZ; NAB; Standard Bank; FirstRand; Emirates NBD; QNB; Al Rajhi; Kidder Peabody; Drexel Burnham Lambert/Drexel; Salomon Brothers/Salomon; First Boston; Dillon Read; Smith Barney; Shearson Lehman/Shearson; PaineWebber; Dean Witter; Donaldson Lufkin and Jenrette/DLJ; Kuhn Loeb; Hambrecht and Quist; Robertson Stephens; Montgomery Securities; Thomas Weisel; Alex. Brown; Bankers Trust; Chemical Bank; Manufacturers Hanover; Chase Manhattan; J.P. Morgan and Co.; Continental Illinois; Bank One; First Chicago; NationsBank; FleetBoston/Fleet; BankBoston; Shawmut; Sovereign Bank; Golden West; IndyMac; Riggs Bank; Franklin National; Penn Square',
  'Medici Bank; Fugger; Barings; Hope and Co.; Warburg/S.G. Warburg; Kleinwort Benson; Hambros; Schroders; Morgan Grenfell; Brown Brothers Harriman/BBH; Lazard Freres; Speyer and Co.; Seligman; Ladenburg Thalmann; Wertheim; Loeb Rhoades; Hutton/E.F. Hutton; Bache; Blyth Eastman; White Weld; Halsey Stuart; Glore Forgan; Hornblower and Weeks; Hayden Stone; Oppenheimer; Gleacher; Wasserstein Perella; Blackstone advisory; Tudor Pickering Holt/TPH; Simmons and Company; Ducera; Ardea; Tidal; Solomon Partners; Ducera Partners; Moelis Australia; Gordon Dyal; Robey Warshaw; Zaoui; Fenchurch; Code Advisors',
  ''),

q('Name a private equity or venture capital firm',
  'Blackstone; KKR; Carlyle; Apollo; Sequoia/Sequoia Capital; Andreessen Horowitz/a16z',
  '',
  'Bain Capital; TPG; Warburg Pincus; Thoma Bravo; Vista Equity/Vista; Silver Lake; Advent International/Advent; Hellman and Friedman/H&F; Ares; Brookfield; CVC; EQT; Permira; Cinven; Apax; General Atlantic; Insight Partners; Tiger Global; SoftBank/Vision Fund; Accel; Benchmark; Kleiner Perkins; Lightspeed; Greylock; Index Ventures; Founders Fund; Y Combinator/YC; General Catalyst; Bessemer; Khosla Ventures; NEA/New Enterprise Associates; GV/Google Ventures; Thrive Capital; Coatue; Lux Capital; First Round; Union Square Ventures/USV; Ribbit Capital; Elliott; Berkshire Hathaway; Pershing Square; Bridgewater; Citadel; Millennium; Point72; Renaissance/Renaissance Technologies; Two Sigma; D.E. Shaw; Man Group',
  'Clayton Dubilier and Rice/CD&R; Leonard Green; Genstar; Veritas Capital; Arcline; Stone Point; Welsh Carson/WCAS; GTCR; Madison Dearborn; Berkshire Partners; THL/Thomas H. Lee; Audax; Charlesbank; Summit Partners; TA Associates; HIG/H.I.G. Capital; Sun Capital; Platinum Equity; Cerberus; Centerbridge; Oaktree; Golden Gate Capital; Francisco Partners; Clearlake; Roark; Searchlight; Sycamore; Gores Group; American Securities; Kohlberg; Onex; OMERS; Ontario Teachers; CPP Investments/CPPIB; GIC; Temasek; Mubadala; ADIA; PIF; KPS; Lone Star; Bain Capital Ventures; Battery Ventures; Spark Capital; Redpoint; IVP; Felicis; Floodgate; SV Angel; Initialized; 8VC; Craft Ventures; Social Capital; DST Global; Dragoneer; ICONIQ; Durable; Altimeter; Addition; Valor; Emergence; Greenoaks; Menlo Ventures; Mayfield; Sutter Hill; Matrix; Foundry; Upfront; Village Global; Neo; Conviction; Elad Gil; Lowercase; Hustle Fund; Harlem Capital; Collaborative Fund; Forerunner; Maveron; Obvious Ventures; Kapor Capital; True Ventures; FirstMark; Primary; RRE; Lerer Hippeau; Greycroft; BoxGroup; Contrary; Abstract; Pear VC; Root Ventures',
  'Kohlberg Kravis Roberts; Forstmann Little; Clayton & Dubilier; Gibbons Green van Amerongen; Wesray; Hicks Muse; Texas Pacific Group; Joseph Littlejohn and Levy/JLL; Vestar; Freeman Spogli; Odyssey Investment; Charterhouse; Saunders Karp; Kelso; Fenway Partners; Harvest Partners; Riverside Company; Sentinel Capital; Trivest; Huron Capital; Wind Point; Pfingsten; Comvest; Brentwood; Levine Leichtman; Shamrock; Kayne Anderson; Littlejohn; Lindsay Goldberg; New Mountain; Siris; Court Square; Snow Phipps; Trilantic; Avista; Water Street; Ampersand; Frazier Healthcare; Linden Capital; Shore Capital; Revelstoke; Webster Equity; Nautic; ABRY; Providence Equity; Vector Capital; Marlin Equity; Accel-KKR; JMI Equity; Spectrum Equity; Great Hill; Parthenon; Bregal; Alpine Investors; Mainsail; Serent; Frontier Growth; Level Equity; PSG; Five Elms; Volition; Sageview; Arctos; RedBird; Sixth Street; Blue Owl; Dyal; HPS; Golub; Owl Rock; Antares; Monroe Capital; Churchill; Twin Brook; Benefit Street; Crescent; Hamilton Lane; StepStone; Adams Street; HarbourVest; Pantheon; Lexington Partners; Coller; Ardian; Partners Group; Neuberger Berman',
  ''),

q('Name an aerospace or defense company',
  'Boeing; Lockheed Martin/Lockheed; Raytheon/RTX; Northrop Grumman/Northrop; SpaceX; General Dynamics',
  '',
  'Airbus; Pratt and Whitney/Pratt & Whitney/Pratt; GE Aerospace/GE/General Electric; Collins Aerospace/Collins; Rolls-Royce; Honeywell; L3Harris/L3/Harris; BAE Systems/BAE; Textron; Bell/Bell Textron; Sikorsky; Gulfstream; Embraer; Bombardier; Cessna; Beechcraft; Piper; Blue Origin; Rocket Lab; Anduril; Palantir; Leidos; Booz Allen/Booz Allen Hamilton; SAIC; CACI; Huntington Ingalls/HII; Electric Boat; Newport News Shipbuilding; Spirit AeroSystems/Spirit; TransDigm; Howmet; Safran; Thales; Leonardo; Dassault; Saab; Rheinmetall; Elbit; Rafael; Israel Aerospace Industries/IAI; Hanwha; Mitsubishi Heavy Industries/MHI; Kawasaki; Virgin Galactic; United Launch Alliance/ULA; Aerojet Rocketdyne/Aerojet; Hexcel; Woodward; Moog; Curtiss-Wright; Parker Aerospace/Parker Hannifin; Eaton; HEICO; Kratos; AeroVironment; General Atomics; Sierra Nevada/SNC; Shield AI; Saronic; Joby; Archer; Relativity Space; Firefly; Axiom Space',
  'McDonnell Douglas; Douglas Aircraft; Grumman; Martin Marietta; Hughes Aircraft/Hughes; Rockwell/Rockwell International; North American Aviation; Convair; Vought; Chance Vought; LTV; Republic Aviation; Fairchild; Bell Aircraft; Bendix; Allison; Teledyne; Litton; TRW; Loral; Orbital Sciences; Orbital ATK; ATK/Alliant Techsystems; Thiokol; Morton Thiokol; Hamilton Standard; Hamilton Sundstrand; Goodrich; Rockwell Collins; UTC/United Technologies; Exelis; ITT; DRS; Cobham; Meggitt; Ultra Electronics; QinetiQ; Babcock; Chemring; GKN; Senior plc; MTU Aero Engines/MTU; MBDA; KNDS; Nexter; Krauss-Maffei Wegmann; Hensoldt; Diehl; Kongsberg; Nammo; Patria; Fincantieri; Naval Group; Navantia; Indra; Avio; Arianespace; OHB; Airbus Defence; Hindustan Aeronautics/HAL; Bharat Electronics; DRDO; AVIC; COMAC; NORINCO; Rostec; Sukhoi; Mikoyan/MiG; Tupolev; Ilyushin; Antonov; Kalashnikov; Almaz-Antey; Embraer Defense; Avibras; Denel; Aselsan; Baykar; Roketsan; TAI/Turkish Aerospace; KAI/Korea Aerospace; LIG Nex1; ST Engineering; Austal; Saab Kockums',
  'Wright Company; Glenn L. Martin Company; Consolidated Aircraft; Vultee; Northrop Corporation; Lockheed Aircraft; Boeing Airplane Company; Stearman; Waco; Ryan Aeronautical; Brewster; Bellanca; Stinson; Aeronca; Taylorcraft; Ercoupe; Luscombe; Mooney; Lake; Helio; Maule; Kaman; Hiller; Piasecki; Vertol; Boeing Vertol; Hughes Helicopters; Robinson Helicopter; Enstrom; Schweizer; Lear; Learjet; Sabreliner; Rockwell Commander; Aero Commander; Grumman American; Swearingen; Fairchild Dornier; Dornier; Fokker; Saab-Scania; Short Brothers/Shorts; de Havilland; de Havilland Canada; Hawker Siddeley; Vickers; Avro; Handley Page; Bristol Aeroplane; Supermarine; Westland; Blackburn; Armstrong Whitworth; Sud Aviation; Aerospatiale; Breguet; Potez; Morane-Saulnier; Messerschmitt; MBB; Junkers; Heinkel; Focke-Wulf; Arado; Macchi; Fiat Aviazione; Caproni; Savoia-Marchetti; Nakajima; Aichi; Kawanishi; Tachikawa'),

q('Name a car model',
  'Mustang/Ford Mustang; Camry/Toyota Camry; Civic/Honda Civic; Corvette; F-150/Ford F-150; Model 3/Tesla Model 3; Jeep Wrangler/Wrangler; Accord/Honda Accord',
  '',
  'Corolla; Prius; RAV4; Highlander; Tacoma; Tundra; 4Runner; Sienna; CR-V; Pilot; Odyssey; Fit; Explorer; Escape; Bronco; Focus; Fusion; Taurus; Expedition; Ranger; Maverick; Silverado; Tahoe; Suburban; Camaro; Malibu; Impala; Equinox; Traverse; Colorado; Charger; Challenger; Durango; Ram 1500/Ram; Grand Cherokee; Cherokee; Model S; Model X; Model Y; Cybertruck; Altima; Sentra; Maxima; Rogue; Pathfinder; Frontier; Leaf; GT-R; 370Z; Elantra; Sonata; Tucson; Santa Fe; Palisade; Kona; Optima; Sorento; Telluride; Soul; Forte; Sportage; Outback; Forester; Impreza; WRX; Crosstrek; Legacy; Miata/MX-5; CX-5; Mazda3; Mazda6; Golf; Jetta; Passat; Beetle; Tiguan; Atlas; GTI; 911/Porsche 911; Cayenne; Macan; Panamera; Taycan; Boxster; Cayman; 3 Series; 5 Series; X5; M3; C-Class; E-Class; S-Class; G-Wagon/G-Class; A4; Q5; R8; TT; Escalade; Navigator; Range Rover; Defender; Mini Cooper; Fiat 500; Model T',
  'Thunderbird; Galaxie; Fairlane; Falcon; Pinto; Gran Torino/Torino; LTD; Crown Victoria/Crown Vic; Grand Marquis; Town Car; Continental; Mark VIII; Probe; Aerostar; Windstar; Freestar; Excursion; Five Hundred; Flex; Edge; EcoSport; Bel Air; Chevelle; Nova; Monte Carlo; El Camino; Caprice; Cavalier; Cobalt; Cruze; Spark; Sonic; Volt; Bolt; Avalanche; Blazer; Trailblazer; S-10; Astro; Lumina; Celebrity; Citation; Vega; Corvair; Chevette; Beretta; Camaro Z28; GTO; Firebird; Trans Am; Grand Prix; Bonneville; Grand Am; Sunfire; Aztek; Vibe; G6; Fiero; Cutlass; Delta 88; Toronado; Alero; Aurora; Intrigue; Bravada; Riviera; Regal; LeSabre; Park Avenue; Century; Skylark; Enclave; Encore; DeVille; Eldorado; Seville; Fleetwood; Catera; CTS; ATS; XT5; Charger Daytona; Viper; Neon; Caravan; Grand Caravan; Dart; Stratus; Intrepid; Magnum; Nitro; Caliber; Avenger; Journey; Dakota; Barracuda/Cuda; Road Runner; Fury; Valiant; Duster; Voyager; Prowler; PT Cruiser; Sebring; 300; Pacifica; LeBaron; New Yorker; Imperial; K-car; Liberty; Commander; Compass; Patriot; Renegade; Gladiator; Wagoneer; CJ; Hummer H1/H1; H2; H3; Supra; Celica; MR2; Corolla Cross; Venza; Avalon; Echo; Yaris; Matrix; Cressida; FJ Cruiser; Land Cruiser; Sequoia; T100; Previa; Element; S2000; Prelude; CRX; del Sol; Insight; Ridgeline; Passport; Integra; Legend; NSX; RSX; TSX; TL; MDX; RDX; 240SX; 300ZX; 280Z; Skyline; Xterra; Armada; Quest; Murano; Juke; Versa; Cube; G35; G37; Q50; QX60; Lancer; Evo/Lancer Evolution; Eclipse; 3000GT; Galant; Outlander; Montero; Pajero; RX-7; RX-8; Protege; MPV; Tribute; Samurai; Sidekick; Vitara; Swift; Baja; SVX; Brat; Tribeca; Ascent; BRZ; Elise; Esprit; Countach; Diablo; Murcielago; Gallardo; Aventador; Huracan; Urus; Testarossa; F40; Enzo; LaFerrari; 458; 488; F8; Roma; Purosangue; Veyron; Chiron; DB5; DB11; Vantage; Phantom; Ghost; Cullinan; Continental GT; Bentayga; Quattroporte; Ghibli; MC20; Stelvio; Giulia; 4C; Spider',
  'Tucker 48; DeLorean DMC-12; Edsel Corsair; Studebaker Avanti/Avanti; Hawk; Lark; Packard Caribbean; Nash Metropolitan/Metropolitan; Rambler American; AMC Gremlin/Gremlin; Pacer; Hornet; Javelin; AMX; Matador; Eagle; Spirit; Concord; Marlin; Ambassador; Kaiser Darrin; Henry J; Crosley Hotshot; Cord 810; Auburn Speedster; Duesenberg Model J; Pierce-Arrow Silver Arrow; Stutz Bearcat; Mercer Raceabout; Hudson Hornet; Hudson Commodore; Willys Jeepster; Jeepster Commando; Scout/International Scout; Travelall; Checker Marathon; Yugo GV; Sterling 825; Merkur XR4Ti; Merkur Scorpio; Daewoo Lanos; Daewoo Nubira; Daewoo Leganza; Suzuki Esteem; Suzuki Aerio; Isuzu Impulse; Isuzu Trooper; Isuzu Rodeo; Isuzu VehiCROSS; Geo Metro/Metro; Geo Tracker; Geo Prizm; Geo Storm; Plymouth Horizon; Dodge Omni; Dodge Aries; Plymouth Reliant; Chrysler TC by Maserati; Cadillac Allante; Cadillac Cimarron; Chevrolet SSR; Chevrolet HHR; Ford Ranchero; Mercury Cougar; Mercury Marauder; Mercury Sable; Mercury Villager; Mercury Zephyr; Mercury Capri; Saturn SL; Saturn Ion; Saturn Sky; Saturn Vue; Saturn Outlook; Saab 900; Saab 9-3; Saab 9-5; Saab 9-7X; Volvo 240; Volvo P1800; Peugeot 405; Peugeot 505; Renault Le Car; Renault Alliance; Fiat X1/9; Fiat 124 Spider; Alfa Romeo Spider; Triumph Spitfire; Triumph TR6; MG MGB/MGB; Austin-Healey Sprite; Austin-Healey 3000; Sunbeam Tiger; Jensen Interceptor; Lotus Seven; Shelby Cobra/Cobra; Shelby GT500; Ford GT40/GT40; Plymouth Superbird; Buick Grand National/Grand National; GNX; Chevy Corvair Monza',
  ''),

q('Name an Apple product',
  'iPhone; iPad; MacBook; AirPods; Apple Watch; iMac; iPod',
  '',
  'MacBook Air; MacBook Pro; Mac mini; Mac Pro; Mac Studio; iPad Pro; iPad Air; iPad mini; iPod Touch; iPod Nano; iPod Shuffle; iPod Classic; AirPods Pro; AirPods Max; Apple TV; HomePod; HomePod mini; AirTag; Apple Pencil; Magic Mouse; Magic Keyboard; Magic Trackpad; Vision Pro/Apple Vision Pro; iPhone SE; Pro Display XDR; Apple Card; Apple Pay; Apple Music; iTunes; iCloud; Siri; FaceTime; iMessage; App Store; Safari; Apple TV+; Apple Arcade; Apple Fitness+; Apple News; Apple Maps; Find My; GarageBand; iMovie; Final Cut Pro; Logic Pro; Keynote; Pages; Numbers; macOS; iOS; Beats; AirPort',
  'Apple II; Apple I; Macintosh; Mac Classic; Lisa; Newton; eMac; iBook; PowerBook; Power Mac; Power Mac G4 Cube/G4 Cube; Xserve; Mac Pro trash can; iSight; AirPort Express; AirPort Extreme; Time Capsule; Apple Cinema Display; Thunderbolt Display; iPod Mini; iPod Hi-Fi; Pippin; QuickTake; eWorld; HyperCard; ClarisWorks; AppleWorks; iWork; iLife; iPhoto; Aperture; Ping; MobileMe; .Mac; iTools; Apple Newton MessagePad/MessagePad; Macintosh Portable; Macintosh SE; Macintosh Plus; Macintosh 128K; Macintosh LC; Performa; Quadra; Centris; Twentieth Anniversary Macintosh; Apple III; Apple IIe; Apple IIc; Apple IIGS; ImageWriter; LaserWriter; StyleWriter; Apple QuickTake; Apple Remote; iPod Socks; Polishing Cloth; Apple Polishing Cloth; FineWoven; MagSafe; Lightning cable; EarPods; Apple Studio Display/Studio Display; Mac Pro wheels; Apple Watch Ultra; Apple Watch Edition; Apple Watch Hermes; iPhone Air; iPhone mini; iPhone 3G; iPhone X',
  'Apple Bandai Pippin; Macintosh TV; Apple Interactive Television Box; PowerCD; Apple Adjustable Keyboard; Apple Extended Keyboard; Apple Desktop Bus; Apple Pro Mouse; Hockey puck mouse; Apple USB Modem; Apple Scanner; Apple Color Printer; Apple Dot Matrix Printer; Apple Lisa 2; Macintosh XL; Macintosh Server; Workgroup Server; Network Server; eMate 300/eMate; Apple Watch Edition gold; HomeKit; CarPlay; Apple Car; Project Titan; Copland; Taligent; Pink; Kaleida; OpenDoc; Cyberdog; Sherlock; Dashboard; Front Row; iWeb; iDVD; Shake; Motion; Color; Soundtrack Pro; DVD Studio Pro; Logic Express; MainStage; Xcode; Swift; SwiftUI; Metal; ARKit; ResearchKit; HealthKit; Clips; Swift Playgrounds; Shazam; Workflow; Dark Sky; Texture',
  ''),

q('Name a retail store or chain',
  'Walmart; Target; Costco; Amazon; Home Depot; Best Buy; CVS; Walgreens',
  '',
  'Lowe\'s; Kroger; Trader Joe\'s; Whole Foods; Publix; Aldi; Safeway; Albertsons; Wegmans; Stop and Shop; ShopRite; Macy\'s; Nordstrom; Kohl\'s; JCPenney; Sears; Kmart; TJ Maxx; Marshalls; HomeGoods; Ross; Burlington; Old Navy; Gap; Bed Bath and Beyond; IKEA; Dollar General; Dollar Tree; Family Dollar; Five Below; Big Lots; Staples; Office Depot; Barnes and Noble; GameStop; Dick\'s Sporting Goods/Dick\'s; Foot Locker; Sephora; Ulta; Bath and Body Works; Victoria\'s Secret; Apple Store; Sam\'s Club; BJ\'s; Rite Aid; 7-Eleven; Wawa; Sheetz; Circle K; Petco; PetSmart; Michaels; Hobby Lobby; Joann; Party City; Toys R Us; Saks Fifth Avenue/Saks; Neiman Marcus; Bloomingdale\'s; Lord and Taylor; Dillard\'s; Belk; Menards; Tractor Supply; AutoZone; Advance Auto Parts; O\'Reilly; Pep Boys; Harbor Freight; Ace Hardware; True Value; Williams-Sonoma; Crate and Barrel; Pottery Barn; Restoration Hardware/RH; West Elm; Pier 1; World Market; Container Store; HEB/H-E-B; Meijer; Hy-Vee; Giant; Food Lion; Winn-Dixie; Piggly Wiggly; Sprouts; Fresh Market; Stew Leonard\'s; Market Basket; Hannaford; Price Chopper',
  'Circuit City; RadioShack; CompUSA; Borders; Blockbuster; Hollywood Video; Tower Records; Sam Goody; Musicland; Virgin Megastore; FAO Schwarz; KB Toys; Zany Brainy; Montgomery Ward; Woolworth\'s; Ames; Bradlees; Caldor; Hills; Zayre; Venture; Mervyn\'s; Gottschalks; Filene\'s; Filene\'s Basement; Jordan Marsh; Marshall Field\'s; Hecht\'s; Kaufmann\'s; Strawbridge\'s; Wanamaker\'s; Gimbels; Abraham and Straus; B. Altman; Bonwit Teller; Alexander\'s; Barneys; Loehmann\'s; Syms; Daffy\'s; Century 21; Linens n Things; Sharper Image; Brookstone; Hammacher Schlemmer; Spiegel; Service Merchandise; Best Products; Lechmere; Hechinger; Builders Square; HQ; Payless ShoeSource/Payless; Thom McAn; Kinney Shoes; Contempo Casuals; Charlotte Russe; Wet Seal; Rave; Deb; Limited Too; Delia\'s; Gadzooks; Pacific Sunwear/PacSun; Hot Topic; Spencer\'s; Claire\'s; Aeropostale; Abercrombie; Hollister; American Apparel; Forever 21; Express; Ann Taylor; Talbots; Chico\'s; J.Jill; Lane Bryant; Torrid; Dress Barn; Christopher and Banks; Stein Mart; Tuesday Morning; Fred\'s; Shopko; Pamida; Gordmans; Boscov\'s; Bon-Ton; Elder-Beerman; Younkers; Carson\'s; Herberger\'s; Von Maur; Fred Meyer; Smith\'s; King Soopers; Ralphs; Vons; Pavilions; Jewel-Osco; Shaw\'s; Acme; Pathmark; A&P; Waldbaum\'s; Grand Union; Food Emporium; Gristedes; D\'Agostino; Fairway; Zabar\'s; Citarella; Eataly; Dean and DeLuca; Balducci\'s',
  'Two Guys; Korvettes; Gertz; Martin\'s; Ohrbach\'s; Orbach\'s; S. Klein; Crazy Eddie; Nobody Beats the Wiz/The Wiz; Newmark and Lewis; Trader Horn; Silo; Highland Superstores; Fretter; Incredible Universe; Tops Appliance City; P.C. Richard; J&R; 47th Street Photo; Herman\'s World of Sporting Goods/Herman\'s; Modell\'s; Champs; Athlete\'s Foot; Just For Feet; Oshman\'s; Sportmart; Sports Authority; Gart Sports; Galyan\'s; Jumbo Sports; Lechters; Conran\'s; Workbench; Domain; Storehouse; This End Up; Bombay Company; Levitz; Seaman\'s; Huffman Koos; Rhodes; Wickes; Food Fair; Jamesway; Rose\'s; G.C. Murphy; McCrory; Kresge; Ben Franklin; Newberry\'s; W.T. Grant; S.S. Kresge; Kress; Neisner\'s; Lamston\'s; Rexall; Thrifty; Osco; Eckerd; Revco; Genovese; Brooks; Phar-Mor; Drug Emporium; Duane Reade',
  ''),

q('Name a hotel chain or brand',
  'Marriott; Hilton; Holiday Inn; Hyatt; Best Western; Motel 6; Four Seasons',
  '',
  'Sheraton; Westin; Ritz-Carlton/Ritz; W Hotels/W; St. Regis; Hampton Inn/Hampton; Courtyard/Courtyard by Marriott; Residence Inn; Fairfield Inn; Embassy Suites; DoubleTree; Waldorf Astoria; Conrad; Hilton Garden Inn; Homewood Suites; Comfort Inn; Quality Inn; Days Inn; Super 8; La Quinta; Red Roof Inn; Ramada; Wyndham; Radisson; InterContinental; Crowne Plaza; Kimpton; Omni; Loews; Fairmont; Mandarin Oriental; Peninsula; Shangri-La; Aman; Rosewood; Park Hyatt; Grand Hyatt; Andaz; Hyatt Regency; Le Meridien; Renaissance; JW Marriott; Aloft; Moxy; Edition; Canopy; Curio; Tapestry; Tru; Home2 Suites; Extended Stay America; Candlewood Suites; Staybridge Suites; Hotel Indigo; Ace Hotel; Hoxton; citizenM; Soho House; 1 Hotel; Nobu Hotel; Bulgari Hotel; Faena; Baccarat; Atlantis; Sandals; Club Med; Disney resorts; Great Wolf Lodge; Airbnb',
  'Travelodge; Econo Lodge; Rodeway Inn; Sleep Inn; Clarion; Cambria Hotels; MainStay Suites; Suburban; WoodSpring Suites; Microtel; Baymont; AmericInn; Wingate; Hawthorn Suites; Howard Johnson/HoJo; Knights Inn; Country Inn and Suites; Park Inn; Drury Inn; Sonesta; Red Lion; GuestHouse; Studio 6; Hyatt Place; Hyatt House; Thompson Hotels; Alila; Miraval; Destination by Hyatt; Unbound Collection; Dream Hotels; Caption; SpringHill Suites; TownePlace Suites; Element; Four Points; Autograph Collection; Luxury Collection; Gaylord; Delta Hotels; AC Hotels; Protea; Signia; LXR; Motto; Spark; Tempo; Graduate; Virgin Hotels; Standard Hotels/The Standard; Thompson; Proper Hotels; Sixty Hotels; Freehand; Generator; Selina; Mama Shelter; Pod Hotels/Pod; Arlo; Yotel; Six Senses; Belmond; Oetker Collection; Dorchester Collection; Raffles; Banyan Tree; Anantara; Oberoi; Taj; Leela; Capella; Jumeirah; Kerzner; One&Only; Como; Auberge; Montage; Pendry; Relais and Chateaux; Small Luxury Hotels; Leading Hotels of the World; Design Hotels; Preferred Hotels',
  'Statler; Treadway Inns; Hospitality Inn; Master Hosts; Imperial 400; Downtowner Motor Inns; Ramada Inn; Howard Johnson\'s Motor Lodge; Hotel Pennsylvania; Esquire Inns; Holiday Inn Holidome/Holidome; Quality Courts; Alamo Plaza Hotel Courts; Tourinns; Superior Motels; Albert Pick Motor Inns; Sheraton Motor Inns; Hilton Inns; Marriott Motor Hotel; Hot Shoppes; Hilton Hawaiian Village; Hotel del Coronado; The Breakers; The Greenbrier; The Broadmoor; The Cloister; Grove Park Inn; Mohonk Mountain House; Grand Hotel Mackinac; Mount Washington Hotel; The Balsams; Wentworth by the Sea; The Homestead; The Hotel Hershey; French Lick; West Baden Springs; The Ahwahnee; Timberline Lodge; Old Faithful Inn; El Tovar; Paradise Inn; Many Glacier Hotel; Glacier Park Lodge; Lake McDonald Lodge; Crater Lake Lodge; Chateau Frontenac; Banff Springs; Chateau Lake Louise; Jasper Park Lodge; Royal York; Hotel Vancouver; Empress Hotel',
  ''),

  );
})();
