(function () {
  const q = Trench.q;
  Trench.add('Food & drink',

q('Name a pasta shape',
  'Spaghetti; Penne; Macaroni; Lasagna/Lasagne; Fettuccine/Fettuccini; Ravioli',
  'Gnocchi; Ramen',
  'Linguine; Rigatoni; Fusilli; Farfalle/Bowtie; Tortellini; Orzo; Angel hair/Capellini; Rotini',
  'Orecchiette; Pappardelle; Cavatappi; Ziti; Bucatini; Tagliatelle; Cannelloni; Manicotti; Conchiglie/Shells; Ditalini; Vermicelli; Elbows',
  'Strozzapreti; Radiatori; Campanelle; Gemelli; Paccheri; Trofie; Casarecce; Mafalde; Cavatelli; Tagliolini; Spaghettini; Mezzaluna; Agnolotti; Tortelloni',
  'Fregola; Anelli; Lumache; Scialatielli; Pici; Malloreddus; Bigoli; Tortiglioni; Busiate; Fileja; Cencioni; Garganelli; Culurgiones; Corzetti'),

q('Name a cheese',
  'Cheddar; Mozzarella; Swiss; American; Parmesan; Brie',
  '',
  'Gouda; Provolone; Feta; Blue cheese/Bleu cheese; Gruyere; Colby; Monterey Jack; Pepper Jack; Cream cheese; Havarti; Muenster; Ricotta; Camembert; Cottage cheese',
  'Gorgonzola; Manchego; Asiago; Halloumi; Roquefort; Stilton; Edam; Emmental/Emmentaler; Fontina; Pecorino; Mascarpone; Cotija; Paneer; Jarlsberg; Raclette; Parmigiano-Reggiano/Parmigiano; Queso fresco',
  'Taleggio; Comte; Boursin; Limburger; Humboldt Fog; Chevre/Goat cheese; Burrata; Brillat-Savarin; Epoisses; Cambozola; Port Salut; Wensleydale; Cheshire; Red Leicester; Colby Jack; String cheese; Oaxaca; Queso blanco',
  'Appenzeller; Tete de Moine; Gjetost; Ossau-Iraty; Vacherin; Reblochon; Mimolette; Stracchino; Idiazabal; Cabrales; Caerphilly; Double Gloucester; Lancashire; Cantal; Munster; Morbier; Livarot; Pont-l\'Eveque; Saint-Nectaire; Beaufort; Abondance; Ricotta salata; Caciocavallo; Scamorza; Grana Padano; Piave; Montasio; Teleme; Brick'),

q('Name a fruit',
  'Apple; Banana; Orange; Strawberry; Grape/Grapes',
  'Tomato; Avocado',
  'Mango; Pineapple; Peach; Pear; Watermelon; Cherry; Lemon; Lime; Blueberry; Raspberry; Kiwi; Plum; Cantaloupe; Papaya; Coconut',
  'Pomegranate; Apricot; Fig; Grapefruit; Blackberry; Cranberry; Honeydew; Nectarine; Tangerine; Clementine; Guava; Passion fruit; Persimmon; Lychee; Dragon fruit; Date; Mulberry',
  'Starfruit/Carambola; Kumquat; Quince; Rambutan; Durian; Jackfruit; Mangosteen; Soursop; Gooseberry; Elderberry; Currant; Boysenberry; Loganberry; Tamarind; Plantain; Cherimoya; Pomelo; Bergamot; Yuzu',
  'Salak; Longan; Jabuticaba; Sapodilla; Ackee; Cloudberry; Lingonberry; Huckleberry; Medlar; Loquat; Feijoa; Pawpaw; Breadfruit; Tamarillo; Sugar apple; Santol; Langsat; Rowan; Sloe; Damson; Greengage; Mirabelle; Pitaya; Sea buckthorn; Salmonberry; Marionberry; Finger lime; Buddha\'s hand; Ugli fruit; Cape gooseberry; Physalis'),

q('Name a cocktail',
  'Margarita; Mojito; Martini; Old Fashioned; Manhattan; Cosmopolitan/Cosmo; Pina Colada',
  '',
  'Daiquiri; Moscow Mule; Bloody Mary; Mai Tai; Negroni; Whiskey Sour; Tequila Sunrise; Long Island Iced Tea; Mimosa; Gin and Tonic/G&T; Screwdriver; White Russian; Sex on the Beach; Aperol Spritz/Spritz',
  'Sazerac; Gimlet; Paloma; Tom Collins; Dark and Stormy; Sidecar; Bellini; Caipirinha; Espresso Martini; Boulevardier; Aviation; Mint Julep; Pisco Sour; Singapore Sling; Rob Roy; Rusty Nail; Black Russian; Kir; Hurricane; Grasshopper; Vodka Soda; Gin Fizz; Amaretto Sour; Cuba Libre; Rum and Coke; Greyhound; Sea Breeze; Cape Codder; Bay Breeze; Harvey Wallbanger; Salty Dog',
  'Last Word; Paper Plane; Corpse Reviver; Vieux Carre; Clover Club; Bramble; French 75; Hemingway Daiquiri; Penicillin; Jungle Bird; Zombie; Painkiller; Blue Hawaii; Gibson; Vesper; Americano; Bijou; Brandy Alexander; Stinger; Godfather; Bobby Burns; Bee\'s Knees; Southside; Gold Rush; Sherry Cobbler; Hot Toddy; Irish Coffee; Tuxedo; Martinez; Blood and Sand',
  'Brandy Crusta; Ramos Gin Fizz; Hanky Panky; Monkey Gland; Remember the Maine; Algonquin; Trinidad Sour; Naked and Famous; Division Bell; Final Ward; Jack Rose; Scofflaw; El Diablo; Cable Car; Industry Sour; Oaxaca Old Fashioned; Improved Whiskey Cocktail; Pegu Club; Ward Eight; Mary Pickford; Pink Squirrel; Fish House Punch; Planter\'s Punch; Pimm\'s Cup; Queen\'s Park Swizzle; Jasmine; Income Tax; Widow\'s Kiss; Tipperary'),

q('Name a type of bread',
  'Sourdough; Baguette; Rye; Ciabatta; Naan; Pita; Focaccia; Bagel; White bread/White; Wheat bread/Wheat',
  '',
  'Brioche; Challah; Pumpernickel; Cornbread; Flatbread; English muffin; Tortilla; Soda bread; Multigrain; Banana bread; Garlic bread; Biscuit; Roti; Chapati; Croissant',
  'Lavash; Injera; Pretzel; Bao; Matzo; Paratha; Fougasse; Boule; Batard; Pane Carasau; Stollen; Panettone; Bannock; Arepa; Hawaiian roll; Dinner roll; Potato bread; Italian bread; French bread; Sandwich bread; Texas toast; Whole wheat; Oat bread',
  'Pao de queijo; Lefse; Limpa; Sangak; Barbari; Taftan; Bammy; Anadama; Kulcha; Puri; Bhatura; Pain au levain; Pain de mie; Schiacciata; Grissini; Pide; Simit; Khachapuri; Kaiser roll; Semmel; Bialy; Cuban bread; Pan de muerto; Pandesal; Tortilla de harina',
  'Pain de campagne; Vollkornbrot; Paximadi; Borodinsky; Zopf; Pogaca; Kisra; Tandoor roti; Rugbrod; Knackebrod; Crispbread; Cobb loaf; Bloomer; Cottage loaf; Barmbrack; Farl; Bara brith; Lardy cake; Bath bun; Chelsea bun; Hot cross bun; Babka; Ekmek; Yufka; Gozleme; Lahmacun'),

q('Name a herb or spice',
  'Cinnamon; Basil; Oregano; Paprika; Parsley; Thyme; Rosemary; Cumin; Garlic; Pepper/Black pepper',
  '',
  'Cilantro/Coriander; Dill; Sage; Nutmeg; Ginger; Turmeric; Mint; Cloves; Chili powder; Cayenne; Bay leaf; Chives; Mustard; Vanilla',
  'Cardamom; Saffron; Tarragon; Fennel; Allspice; Star anise; Marjoram; Lemongrass; Fenugreek; Curry leaf; Sumac; Za\'atar; Anise; Caraway; Juniper; Red pepper flakes; Onion powder; Celery seed; Poppy seed; Sesame; Curry powder; Garam masala; Italian seasoning; Herbes de Provence',
  'Asafoetida; Mace; Galangal; Annatto; Epazote; Lovage; Savory; Borage; Chervil; Sorrel; Nigella; Ajwain; Amchur; Long pepper; Szechuan pepper/Sichuan pepper; Grains of paradise; Lemon balm; Lemon verbena; Shiso; Perilla; Thai basil; Holy basil/Tulsi; Wasabi; Horseradish; Cassia; Tonka bean',
  'Mahleb; Kaffir lime leaf; Makrut lime; Pandan; Vadouvan; Berbere; Ras el hanout; Baharat; Dukkah; Zhug; Shichimi togarashi; Togarashi; Sansho; Aleppo pepper; Urfa biber; Piment d\'Espelette; Hyssop; Rue; Angelica; Costmary; Woodruff; Mastic; Kokum; Black cardamom; Salep'),

q('Name a soft drink brand',
  'Coca-Cola/Coke; Pepsi; Sprite; Dr Pepper/Dr. Pepper; Mountain Dew; Fanta',
  '',
  '7UP/7 Up; A&W; Canada Dry; Schweppes; Sunkist; Barq\'s; Squirt; Crush; Mello Yello; Sierra Mist; Mug; Root beer',
  'Vernors; Faygo; Jarritos; IBC; Cheerwine; Moxie; Tab; Fresca; Shasta; Big Red; Sprecher; Mr. Pibb/Mr Pibb; Dad\'s; Orangina; Irn-Bru; Inca Kola; Diet Coke; Coke Zero; Pepsi Max; Zevia; Surge; Vault; Sun Drop; Cherry Coke',
  'Ale-8-One; Dr. Brown\'s/Dr Browns; Fentimans; Jones Soda; Boylan; Foxon Park; Virgil\'s; Bundaberg; Kofola; Mezzo Mix; Ting; Mirinda; Tango; Appletiser; Vimto; Lilt; Tizer; Lucozade; Ribena; Bubble Up; Nehi; RC Cola; Royal Crown; Dr Enuf; Tahitian Treat; Cott; Clearly Canadian; Slice',
  'Ramune; Kickapoo Joy Juice; Guarana Antarctica; Frostie; Sioux City; Fitz\'s; Hansen\'s; Reed\'s; Maine Root; Fever-Tree; Seagram\'s'),

q('Name a candy bar',
  'Snickers; Kit Kat; Twix; Reese\'s/Reeses; Hershey\'s/Hershey; Milky Way; 3 Musketeers/Three Musketeers',
  '',
  'Butterfinger; Baby Ruth; Mounds; Almond Joy; Payday; Crunch/Nestle Crunch; Heath; Skor; Whatchamacallit; 100 Grand; Mr. Goodbar/Mr Goodbar; Oh Henry; Toblerone; Cadbury',
  'Dairy Milk; Bounty; Mars; Twirl; Flake; Wispa; Aero; Lion; Kinder Bueno; Take 5; Zagnut; Clark Bar/Clark; Charleston Chew; Chunky; Rolo; Tootsie Roll; Milkybar; Fudge; Crunchie; Curly Wurly; Double Decker; Freddo; Picnic; Boost; Galaxy; Ferrero Rocher; Lindt; Godiva; Ghirardelli; Kinder',
  'Idaho Spud; Abba-Zaba; Mallo Cup; Cup-O-Gold; Big Hunk; Chick-O-Stick; Valomilk; Bit-O-Honey; Violet Crumble; Caramac; Marathon; Pearson\'s Nut Goodie; Nut Goodie; U-No; Forever Yours; Cherry Mash; Goo Goo Cluster; Moon Pie; PB Max',
  'Snirkles; Rocky Road; Squirrel Nut Zippers; Necco Wafers; Sugar Daddy; Sugar Babies; Slo Poke; Black Cow; Hot Tamales; Mary Jane; Jujyfruits; Bonomo Turkish Taffy; Turkish Taffy; Lik-M-Aid; Pixy Stix; Sweetarts; Charms; Dots; Mike and Ike; Jordan Almonds'),

q('Name a Japanese dish',
  'Sushi; Ramen; Tempura; Teriyaki; Sashimi; Miso soup/Miso; Udon',
  '',
  'Yakitori; Tonkatsu; Katsu; Gyoza; Edamame; Takoyaki; Okonomiyaki; Soba; Onigiri; Mochi; Sukiyaki; Shabu-shabu/Shabu shabu; Donburi; Katsudon; Unagi; Teppanyaki; Bento; Wasabi; Maki',
  'Yakisoba; Tamagoyaki; Chawanmushi; Oden; Natto; Tsukemen; Karaage; Gyudon; Oyakodon; Nigiri; Temaki; Chirashi; Kaiseki; Curry rice/Japanese curry; Katsu curry; Sekihan; Tofu; Agedashi tofu; Dango; Taiyaki; Dorayaki; Hibachi; Sake; Tonkotsu',
  'Nabe; Motsunabe; Hitsumabushi; Monjayaki; Kushikatsu; Zaru soba; Omurice; Hayashi rice; Daifuku; Anmitsu; Fugu; Yudofu; Soba noodles; Kitsune udon; Tempura soba; Tanuki; Tsukune; Yakiniku; Negima; Shiokara; Umeboshi; Tsukemono; Kakiage; Zosui; Gyutan; Wagyu',
  'Tonjiru; Nikujaga; Ochazuke; Champon; Hoto; Mizutaki; Sanuki udon; Inaniwa udon; Sasamaki; Kamameshi; Mentaiko; Karashi mentaiko; Basashi; Sakuramochi; Namagashi; Kakigori; Ikayaki; Gindara; Saikyo yaki; Hiyayakko; Hiyashi chuka; Taimeshi; Shirasu; Sanma; Anago; Kibinago; Funazushi; Kiritanpo; Wanko soba'),

q('Name a breakfast cereal',
  'Cheerios; Frosted Flakes; Froot Loops; Lucky Charms; Cap\'n Crunch/Captain Crunch; Corn Flakes; Cinnamon Toast Crunch; Rice Krispies',
  '',
  'Raisin Bran; Honey Nut Cheerios; Special K; Wheaties; Trix; Cocoa Puffs; Apple Jacks; Kix; Honeycomb; Fruity Pebbles; Cocoa Pebbles; Life; Chex; Grape-Nuts/Grape Nuts; Frosted Mini-Wheats/Mini-Wheats; Golden Grahams; Count Chocula',
  'Product 19; Total; Cracklin\' Oat Bran; Honey Bunches of Oats; Reese\'s Puffs; Cookie Crisp; Waffle Crisp; Corn Pops; Krave; Fiber One; All-Bran; Shredded Wheat; Smacks/Honey Smacks; Franken Berry; Boo Berry; Oatmeal Squares; Cap\'n Crunch\'s Crunch Berries/Crunch Berries; Peanut Butter Captain Crunch; Cocoa Krispies; Frosted Cheerios; Multigrain Cheerios; Apple Cinnamon Cheerios; Berry Berry Kix; Corn Chex; Rice Chex; Wheat Chex',
  'Quisp; Quake; Golden Crisp; Crispix; Mueslix; Alpha-Bits; Kaboom; Malt-O-Meal; Puffa Puffa Rice; Post Toasties; Cream of Wheat; Wheatena; Cheerios Oat Crunch; Sugar Smacks; Oreo O\'s; Dino Pebbles; Mini Swirlz; King Vitaman; Sugar Crisp; Sugar Pops; Pop Tarts Cereal; Wheat Honeys; Rice Honeys; Corn Bran; Honey Combs; Cinnamon Life; Fruity Cheerios; Frosted Shredded Wheat',
  'Freakies; Sir Grapefellow; Pac-Man cereal; Banana Frosted Flakes; Fruit Brute; Yummy Mummy; Fruity Marshmallow Krispies; Rice Krinkles; Frute Brute; Wackies; Twinkles; Smurfberry Crunch; Mr. T cereal; Nesquik; Pebbles Boulders; Marshmallow Mateys; Honey Graham Oh\'s; Teenage Mutant Ninja Turtles cereal'),

q('Name a variety of apple',
  'Granny Smith; Gala; Fuji; Honeycrisp; Red Delicious; Golden Delicious; McIntosh/Mcintosh',
  '',
  'Pink Lady/Cripps Pink; Braeburn; Jazz; Cortland; Empire; Jonagold; Envy; Cosmic Crisp; Jonathan; Macoun',
  'Rome; Pippin; Cameo; Winesap; Crispin/Mutsu; Ambrosia; Idared; Gravenstein; Northern Spy; Baldwin; Fireside; Ginger Gold; Cox\'s Orange Pippin/Cox; Bramley; Paula Red; Spartan; Liberty; Akane; Kiku; Opal; Rubinette',
  'Arkansas Black; Rhode Island Greening; Roxbury Russet; Newtown Pippin; Esopus Spitzenburg; Ashmead\'s Kernel; Egremont Russet; Discovery; Zestar; Snapdragon; RubyFrost; Kanzi; SweeTango; Sundowner; Wealthy; Pazazz; Lodi; Yellow Transparent; Duchess of Oldenburg; Wolf River; Black Twig; Calville Blanc; Api Etoile; Reine des Reinettes; Belle de Boskoop; Elstar; Topaz; Pinova; Piñata; Hewes Crab; Kingston Black; Dabinett; Yarlington Mill; Foxwhelp; Harry Masters Jersey; Michelin; Brown Snout; Redstreak; Tom Putt; Ellison\'s Orange; Margil; Ribston Pippin; Lord Lambourne; Worcester Pearmain; Laxton\'s Superb; Blenheim Orange; Peasgood\'s Nonsuch; Catshead; Keswick Codlin; Annie Elizabeth; Howgate Wonder; Lane\'s Prince Albert; Stirling Castle; Warner\'s King; Court Pendu Plat; Pitmaston Pineapple'),

q('Name a fast-food or chain restaurant',
  'McDonald\'s/McDonalds; Burger King; Wendy\'s/Wendys; Taco Bell; KFC; Subway; Chick-fil-A',
  '',
  'Domino\'s/Dominos; Pizza Hut; Popeyes; Chipotle; Arby\'s/Arbys; Sonic; Dunkin/Dunkin\' Donuts; Starbucks; Five Guys; In-N-Out; Jack in the Box; Panera; Papa John\'s; Dairy Queen; Carl\'s Jr; Applebee\'s; Olive Garden; Chili\'s; Outback',
  'Whataburger; Del Taco; Panda Express; White Castle; Culver\'s; Shake Shack; Raising Cane\'s/Canes; Zaxby\'s; Wingstop; Little Caesars; Jersey Mike\'s; Jimmy John\'s; Qdoba; Moe\'s; Hardee\'s; Checkers; Rally\'s; Bojangles; El Pollo Loco; Denny\'s; IHOP; Waffle House; Red Lobster; Cheesecake Factory; Texas Roadhouse; Hooters; Red Robin; Cracker Barrel',
  'Krystal; Steak n Shake; Freddy\'s; Smashburger; Church\'s; Long John Silver\'s; Captain D\'s; Wienerschnitzel; Tim Hortons; Firehouse Subs; Potbelly; Cook Out; Jollibee; MOD Pizza; Sweetgreen; Cava; Noodles and Company; Au Bon Pain; Bruegger\'s; Einstein Bros; Krispy Kreme; Tropical Smoothie; Smoothie King; Jamba Juice; Cold Stone; Baskin-Robbins; Friendly\'s; Bob Evans; Perkins; Golden Corral; Ruby Tuesday; TGI Fridays; Bennigan\'s',
  'Fatburger; Habit Burger; Maid-Rite; Runza; Skyline Chili; Gold Star Chili; Braum\'s; Burgerville; Zippy\'s; Pal\'s; Back Yard Burgers; Fazoli\'s; Sbarro; Nathan\'s Famous/Nathan\'s; Villa Pizza; Cici\'s; Marco\'s; Hungry Howie\'s; Papa Murphy\'s; Round Table; Boston Market; Roy Rogers; Sizzler'),

q('Name a wine grape variety',
  'Chardonnay; Merlot; Cabernet Sauvignon/Cabernet; Pinot Noir; Pinot Grigio; Sauvignon Blanc; Riesling',
  '',
  'Malbec; Syrah/Shiraz; Zinfandel; Moscato/Muscat; Pinot Gris; Sangiovese; Chenin Blanc; Gewurztraminer; Tempranillo; Grenache; Viognier; Cabernet Franc',
  'Nebbiolo; Barbera; Gamay; Albarino; Gruner Veltliner; Semillon; Petit Verdot; Mourvedre; Carmenere; Montepulciano; Primitivo; Trebbiano; Garganega; Verdejo; Vermentino; Torrontes; Pinotage; Carignan; Cinsault',
  'Aglianico; Nero d\'Avola; Dolcetto; Lambrusco; Cortese; Fiano; Greco; Falanghina; Furmint; Blaufrankisch; Zweigelt; Xinomavro; Assyrtiko; Touriga Nacional; Tannat; Marsanne; Roussanne; Picpoul; Melon de Bourgogne; Petite Sirah; Pinot Blanc; Pinot Meunier; Meunier; Arneis; Friulano',
  'Saperavi; Rkatsiteli; Kadarka; Plavac Mali; Agiorgitiko; Mencia; Godello; Bobal; Graciano; Negroamaro; Pecorino; Refosco; Teroldego; Lagrein; Schiava; Verdicchio; Vernaccia; Muller-Thurgau; Silvaner; Scheurebe; Bacchus; Norton; Concord; Catawba; Niagara; Vidal Blanc; Seyval Blanc'),

q('Name a pizza topping',
  'Pepperoni; Cheese; Sausage; Mushrooms/Mushroom; Onions/Onion; Peppers/Green peppers; Olives/Black olives',
  '',
  'Bacon; Pineapple; Ham; Extra cheese; Spinach; Tomatoes; Jalapenos; Chicken; Basil; Garlic',
  'Anchovies; Ground beef; Meatballs; Artichoke; Ricotta; Feta; Arugula; Prosciutto; Salami; Capers; Buffalo chicken; BBQ chicken; Broccoli; Eggplant; Zucchini; Corn',
  'Egg; Pesto; Goat cheese; Truffle; Hot honey; Fig; Clams; Sun-dried tomatoes; Roasted garlic; Gorgonzola; Soppressata; Nduja; Pancetta; Red onion; Banana peppers; Pepperoncini',
  'Calabrian chili; Burrata; Bresaola; Speck; Pickles; Mac and cheese; French fries; Potato; Cheeseburger; Duck; Kimchi; Edamame; Lardons; Squash blossoms; Radicchio; Fennel sausage; Lamb; Sweet potato; Brussels sprouts; Kale; Pistachio; Nutella; Pear; Honey'),

q('Name a coffee drink',
  'Latte; Cappuccino; Espresso; Americano; Mocha',
  '',
  'Macchiato; Flat white; Cold brew; Iced coffee; Frappuccino; Cortado; Drip coffee; Decaf; Caramel macchiato; Iced latte; Pumpkin spice latte/PSL',
  'Affogato; Doppio; Ristretto; Lungo; Red eye; Cafe au lait; Irish coffee; Turkish coffee; Cafe Bombon; Con panna; Breve; Nitro; French press; Pour over; Cafe con leche; Vanilla latte; Black coffee',
  'Galao; Cafe cubano/Cuban coffee; Cafecito; Vienna; Einspanner; Piccolo; Mazagran; Cafe de olla; Dalgona; Long black; Gibraltar; Cafe zorro; Black eye; Dead eye; Greek coffee; Frappe; Cafe noisette; Noisette',
  'Kopi luwak; Kopi tubruk; Ca phe sua da/Vietnamese coffee; Yuanyang; Palazzo; Marocchino; Bicerin; Ipoh white coffee; Cafe Touba; Sanka; Egg coffee; Ca phe trung; Cafe brulot; Corretto; Caffe shakerato; Shakerato'),

  );
})();
