(function () {
  const q = Trench.q;
  Trench.add('Geography',

q('Name a country in Europe',
  'France; Germany; Italy; Spain; United Kingdom/UK/England/Britain/Great Britain',
  'Russia; Turkey',
  'Portugal; Greece; Netherlands/Holland; Sweden; Norway; Poland; Switzerland; Ireland; Belgium; Austria; Denmark; Finland',
  'Hungary; Croatia; Czech Republic/Czechia; Romania; Bulgaria; Serbia; Ukraine; Iceland; Slovakia; Slovenia; Lithuania; Latvia; Estonia',
  'Luxembourg; Malta; Albania; North Macedonia/Macedonia; Montenegro; Moldova; Belarus; Bosnia and Herzegovina/Bosnia; Cyprus',
  'San Marino; Liechtenstein; Andorra; Monaco; Vatican City/Vatican/Holy See; Kosovo'),

q('Name a country in Africa',
  'Egypt; Nigeria; South Africa; Kenya; Morocco',
  '',
  'Ethiopia; Ghana; Algeria; Tanzania; Uganda; Senegal; Tunisia; Libya; Zimbabwe',
  'Angola; Mozambique; Zambia; Cameroon; Ivory Coast/Cote d\'Ivoire; Sudan; Namibia; Botswana; Madagascar; Mali; Rwanda; Congo/Republic of the Congo; Democratic Republic of the Congo/DRC/DR Congo',
  'Malawi; Niger; Chad; Gabon; Benin; Togo; Burkina Faso; Sierra Leone; Liberia; Mauritania; Somalia; Mauritius',
  'Eritrea; Djibouti; Lesotho; Eswatini/Swaziland; Comoros; Seychelles; Sao Tome and Principe; Cape Verde/Cabo Verde; Equatorial Guinea; Burundi; Gambia; Guinea-Bissau; Guinea; South Sudan; Central African Republic'),

q('Name a country in Asia',
  'China; India; Japan; South Korea/Korea; Thailand; Vietnam',
  '',
  'Indonesia; Philippines; Malaysia; Singapore; Pakistan; Saudi Arabia; Iran; Israel',
  'Nepal; Sri Lanka; Bangladesh; Cambodia; Laos; Mongolia; Iraq; Jordan; Lebanon; Syria; Kazakhstan; Taiwan; North Korea; Afghanistan; United Arab Emirates/UAE; Qatar; Kuwait',
  'Myanmar/Burma; Bhutan; Uzbekistan; Oman; Yemen; Brunei; Kyrgyzstan; Tajikistan; Turkmenistan; Azerbaijan; Armenia',
  'Maldives; Bahrain; East Timor/Timor-Leste'),

q('Name a river anywhere in the world',
  'Nile; Amazon; Mississippi; Thames; Hudson',
  '',
  'Danube; Rhine; Seine; Yangtze; Ganges; Colorado; Missouri; Volga; Tigris; Euphrates; Jordan',
  'Mekong; Niger; Congo; Zambezi; Orinoco; Ohio; Rio Grande; Columbia; Yellow River/Huang He; Indus; Elbe; Loire; Po; Tiber; Brahmaputra; Potomac; Delaware; Connecticut; Charles; Shannon; Severn',
  'Irrawaddy; Murray; Limpopo; Dnieper; Oder; Vistula; Rhone; Ebro; Tagus; Yukon; Mackenzie; Lena; Ob; Amur; Snake; Arkansas; Tennessee; Platte; Paraguay; Parana; Rio de la Plata; Magdalena; Moselle; Main; Neckar; Garonne; Dordogne; Don; Dniester; Ural; Mersey; Tyne; Clyde',
  'Volta; Senegal; Sepik; Fly; Darling; Salween; Kolyma; Yenisei; Okavango; Orange; Cuyahoga; Kuskokwim; Pecos; Wabash; Susquehanna; Merrimack; Kennebec; Penobscot; Suwannee; Chattahoochee; Tocantins; Xingu; Madeira; Purus; Ucayali; Maranon; Sava; Drava; Tisza; Prut; Narva; Daugava; Neman; Vltava; Maas; Scheldt; Guadalquivir; Duero; Minho'),

q('Name a US state that doesn\'t touch an ocean',
  'Colorado; Nevada; Arizona; Utah',
  '',
  'Kansas; Nebraska; Iowa; Tennessee; Kentucky; Oklahoma; Montana; Idaho; Wyoming; New Mexico',
  'Minnesota; Wisconsin; Missouri; Ohio; Illinois; Indiana; Michigan; Arkansas; Pennsylvania',
  'Vermont; North Dakota; South Dakota',
  'West Virginia'),

q('Name a world capital city',
  'Paris; London; Tokyo; Washington/Washington DC/Washington D.C.; Rome; Berlin; Moscow; Beijing; Madrid',
  '',
  'Cairo; Ottawa; Canberra; Lisbon; Athens; Vienna; Dublin; Seoul; Bangkok; Buenos Aires; Mexico City; Brasilia; New Delhi/Delhi',
  'Nairobi; Oslo; Stockholm; Helsinki; Warsaw; Prague; Budapest; Lima; Bogota; Santiago; Havana; Hanoi; Jakarta; Manila; Kyiv/Kiev; Copenhagen; Brussels; Amsterdam; Bern/Berne',
  'Addis Ababa; Accra; Dakar; Kampala; Lusaka; Harare; Windhoek; Quito; La Paz; Montevideo; Asuncion; Caracas; Kathmandu; Colombo; Dhaka; Tashkent; Baku; Tbilisi; Yerevan; Reykjavik; Tallinn; Riga; Vilnius',
  'Ulaanbaatar; Thimphu; Vientiane; Naypyidaw; Bishkek; Dushanbe; Ashgabat; Nouakchott; Ouagadougou; Bamako; Niamey; Ndjamena; Bujumbura; Asmara; Djibouti; Maseru; Mbabane; Valletta; Vaduz; Andorra la Vella; Podgorica; Skopje; Tirana; Chisinau; Sarajevo; Port Moresby; Honiara; Apia; Suva; Port Vila'),

q('Name a mountain or peak',
  'Everest/Mount Everest; Kilimanjaro; Denali; Fuji/Mount Fuji; Matterhorn; Mont Blanc',
  '',
  'K2; Rainier/Mount Rainier; Whitney/Mount Whitney; Elbrus; Aconcagua; Olympus/Mount Olympus; Vesuvius; Etna; Sinai; Kosciuszko; Rushmore; Hood/Mount Hood',
  'Kangchenjunga; Lhotse; Makalu; Annapurna; Cho Oyu; Eiger; Jungfrau; Ben Nevis; Snowdon; Teide; St. Helens/Mount St Helens; Shasta; Ararat; Elbert; Washington/Mount Washington; Logan; Cook; Zugspitze; Pikes Peak; Katahdin; Mitchell',
  'Nanga Parbat; Dhaulagiri; Manaslu; Gasherbrum; Broad Peak; Vinson; Stanley; Toubkal; Cotopaxi; Chimborazo; Huascaran; Popocatepetl; Kinabalu; Pico de Orizaba; Grossglockner; Triglav; Musala; Kenya; Meru; Ruwenzori; Erebus; Fitz Roy; Cerro Torre; Huayna Potosi; Ojos del Salado',
  'Mawenzi; Kebnekaise; Galdhopiggen; Gerlach; Rysy; Moldoveanu; Hvannadalshnukur; Aoraki; Puncak Jaya; Carstensz Pyramid; Vinson Massif; Ama Dablam; Pumori; Nuptse; Baruntse; Machapuchare; Kailash; Tirich Mir; Rakaposhi; Ushba; Kazbek; Damavand; Sabalan; Mulhacen; Aneto; Monte Rosa; Dom; Weisshorn; Finsteraarhorn; Ortler'),

q('Name an island',
  'Hawaii; Cuba; Iceland; Madagascar; Greenland; Ireland; Jamaica',
  'Australia',
  'Sicily; Sardinia; Crete; Bali; Java; Tahiti; Fiji; Manhattan; Long Island; Puerto Rico; Bermuda; Corsica; Cyprus; Malta; Maui; Great Britain/Britain',
  'Borneo; Sumatra; Sri Lanka; Tasmania; Newfoundland; Honshu; Hokkaido; Mallorca/Majorca; Ibiza; Capri; Santorini; Mykonos; Rhodes; Zanzibar; Mauritius; Barbados; Aruba; Bahamas; Nantucket; Martha\'s Vineyard; Staten Island; Key West; Oahu; Kauai; Cozumel; Phuket',
  'Corfu; Elba; Skye; Anglesey; Isle of Wight; Jersey; Guernsey; Faroe Islands/Faroes; Svalbard; Sakhalin; Bora Bora; Samoa; Tonga; Guam; Easter Island; Galapagos; Madeira; Azores; Tenerife; Menorca; Minorca; Lesbos; Naxos; Paros; Ischia; Isle of Man; Orkney; Shetland; Hebrides; Lewis; Islay; Tobago; Trinidad; Hispaniola; Rhode Island; Block Island; Roanoke Island; Ellis Island; Alcatraz',
  'Socotra; Tristan da Cunha; Saint Helena/St Helena; Pitcairn; Kiritimati; Lampedusa; Pantelleria; Stromboli; Lindisfarne; Iona; Staffa; Rockall; Heligoland; Gotland; Bornholm; Oland; Sable Island; Anticosti; Baffin Island; Ellesmere; Victoria Island; Novaya Zemlya; Wrangel; Kodiak; Unalaska; Midway; Wake Island; Nauru; Tuvalu; Palau; Yap; Chuuk; Truk; Bikini; Kwajalein; Rapa Nui; Juan Fernandez; Chiloe; Tierra del Fuego; South Georgia; Falklands; Bouvet; Kerguelen; Heard Island'),

q('Name a lake',
  'Superior/Lake Superior; Michigan/Lake Michigan; Erie/Lake Erie; Tahoe/Lake Tahoe; Victoria/Lake Victoria; Huron/Lake Huron; Ontario/Lake Ontario; Titicaca/Lake Titicaca; Como/Lake Como; Geneva/Lake Geneva; Loch Ness',
  '',
  'Baikal/Lake Baikal; Tanganyika/Lake Tanganyika; Great Salt Lake; Champlain/Lake Champlain; Placid/Lake Placid; Winnipesaukee; Okeechobee/Lake Okeechobee; Garda/Lake Garda; Lucerne/Lake Lucerne; Constance/Lake Constance; Windermere; Chad/Lake Chad; Malawi/Lake Malawi; Lake Powell; Lake Mead; Lake of the Woods',
  'Maracaibo/Lake Maracaibo; Nicaragua/Lake Nicaragua; Ladoga; Onega; Balaton; Bled/Lake Bled; Lake Louise; Powell; Mead; Pontchartrain; Itasca; Crater Lake; Eyre/Lake Eyre; Taupo/Lake Taupo; Toba; Biwa; Van/Lake Van; Urmia; Aral Sea; Caspian Sea; Lake George; Lake Winnebago; Lake Lanier; Lake Havasu; Lake Pend Oreille; Lake Chelan; Lake Washington; Lake Oahe; Seneca/Seneca Lake; Cayuga; Lake Wylie; Lake Norman',
  'Vanern; Vattern; Saimaa; Peipus; Ohrid; Prespa; Neusiedl; Lugano; Maggiore/Lake Maggiore; Annecy; Atitlan; Chapala; Natron; Turkana; Kivu; Albert; Edward; Kariba; Nasser; Lac Leman; Zurich/Lake Zurich; Lake Thun; Lake Brienz; Neuchatel; Bodensee; Chiemsee; Starnberg; Ullswater; Coniston; Derwentwater; Lough Neagh; Lough Erne; Lough Derg; Lomond/Loch Lomond; Loch Awe; Loch Tay; Loch Katrine',
  'Hovsgol; Issyk-Kul; Khanka; Qinghai; Dongting; Poyang; Nam Co; Sevan; Vostok; Wakatipu; Te Anau; Rotorua; Torrens; Gairdner; Lake Gregory; Lake Argyle; Lake Burley Griffin; Lake Mungo; Lake Nyasa; Lake Rukwa; Lake Mweru; Lake Bangweulu; Lake Tana; Lake Abaya; Lake Nakuru; Lake Naivasha; Lake Baringo; Lake Bogoria; Lake Manyara; Lake Eyasi'),

q('Name a desert',
  'Sahara; Gobi; Mojave; Kalahari; Arabian',
  'Antarctica',
  'Atacama; Sonoran; Negev; Namib; Thar; Great Victoria; Painted Desert; Chihuahuan; Death Valley',
  'Great Basin; Syrian; Taklamakan; Simpson; Gibson; Sinai; Nubian; Libyan; Patagonian; Judean; Colorado Desert; Great Sandy; Arctic',
  'Karakum; Kyzylkum; Dasht-e Kavir; Dasht-e Lut; Ordos; Badain Jaran; Rub al Khali/Empty Quarter; Nefud; Tanami; Little Sandy; Sturt Stony; Black Rock; Tabernas; Karoo; Sechura',
  'Danakil; Tenere; Ogaden; Bardenas Reales; Cholistan; Thal; Monte; Gran Desierto de Altar; Sahel; Gurbantunggut; Tengger; Mu Us; Kumtag; Dzungarian; Alashan'),

q('Name a US national park',
  'Yellowstone; Yosemite; Grand Canyon; Zion; Glacier; Acadia; Arches; Grand Teton; Great Smoky Mountains/Smoky Mountains/Smokies; Joshua Tree',
  '',
  'Bryce Canyon/Bryce; Rocky Mountain; Olympic; Everglades; Death Valley; Sequoia; Denali; Badlands; Shenandoah; Canyonlands; Crater Lake; Mount Rainier/Rainier; Haleakala',
  'Capitol Reef; Mesa Verde; Big Bend; Redwood; Kings Canyon; Saguaro; Carlsbad Caverns; Petrified Forest; Cuyahoga Valley; Hot Springs; Mammoth Cave; Great Sand Dunes; Channel Islands; Lassen Volcanic/Lassen; Biscayne; Congaree; Voyageurs',
  'Guadalupe Mountains; Theodore Roosevelt; Wind Cave; Black Canyon of the Gunnison; Great Basin; Isle Royale; Katmai; Kenai Fjords; Gates of the Arctic; Glacier Bay; Lake Clark; Wrangell-St. Elias/Wrangell St Elias; Kobuk Valley; Dry Tortugas; Pinnacles; Indiana Dunes',
  'New River Gorge; Gateway Arch; Virgin Islands; American Samoa; Hawaii Volcanoes; White Sands; North Cascades; Mount St Helens'),

q('Name a Canadian province or territory',
  'Ontario; Quebec; British Columbia; Alberta',
  '',
  'Manitoba; Saskatchewan; Nova Scotia',
  'New Brunswick; Newfoundland and Labrador/Newfoundland/Labrador; Yukon',
  'Prince Edward Island/PEI; Northwest Territories',
  'Nunavut'),

q('Name a Caribbean island or island nation',
  'Jamaica; Cuba; Bahamas; Puerto Rico; Haiti',
  '',
  'Dominican Republic; Barbados; Trinidad and Tobago/Trinidad; Aruba; Cayman Islands/Grand Cayman',
  'Saint Lucia/St Lucia; Antigua and Barbuda/Antigua; Grenada; Martinique; Guadeloupe; Curacao; Turks and Caicos; Saint Kitts and Nevis/St Kitts; Dominica; Bonaire; Tobago; St Thomas; Hispaniola',
  'Saint Vincent and the Grenadines/St Vincent; Anguilla; Montserrat; Saint Martin/St Martin/Sint Maarten; Saint Barthelemy/St Barts; British Virgin Islands/Tortola; US Virgin Islands; Nevis; Barbuda; St Croix; St John; Virgin Gorda; Cozumel',
  'Saba; Sint Eustatius/Statia; Mustique; Bequia; Carriacou; Culebra; Vieques; Roatan; Little Cayman; Providenciales; Grand Turk; Jost Van Dyke; Anegada; Canouan; Union Island; Petit St Vincent; Mayreau; Isla de la Juventud; Cayo Largo; Great Exuma; Eleuthera; Andros; Abaco; Bimini'),

q('Name a European city that is not a capital',
  'Barcelona; Milan; Munich; Venice; Florence; Manchester; Liverpool',
  '',
  'Marseille; Lyon; Hamburg; Frankfurt; Naples; Turin; Seville; Valencia; Porto; Geneva; Zurich; Glasgow; Birmingham; Salzburg; Rotterdam; Nice; Cologne',
  'Bordeaux; Toulouse; Lille; Bologna; Verona; Genoa; Bilbao; Granada; Malaga; Antwerp; Bruges; Ghent; Gothenburg; Krakow; Gdansk; Dresden; Stuttgart; Dusseldorf; Hanover; Leipzig; Nuremberg; Pisa; Siena; Cannes; Monaco',
  'Split; Dubrovnik; Plovdiv; Cluj-Napoca/Cluj; Brno; Salamanca; Cordoba; Strasbourg; Rennes; Nantes; Lausanne; Basel; Bergen; Tromso; Malmo; Aarhus; Tampere; Turku; Thessaloniki; Lviv; Odesa/Odessa; Cork; Galway; Leeds; Sheffield; Bristol; Newcastle; Oxford; Cambridge; Bath; York; Brighton',
  'Wroclaw; Poznan; Lodz; Debrecen; Timisoara; Kosice; Maribor; Graz; Innsbruck; Linz; Trondheim; Stavanger; Oulu; Gdynia; Rijeka; Varna; Burgas; Kaunas; Tartu; Daugavpils; Maastricht; Utrecht; Eindhoven; Groningen; Liege; Charleroi; Gijon; Vigo; Zaragoza; Pamplona; San Sebastian; Palma; Braga; Coimbra; Faro; Lucca; Perugia; Trieste; Bari; Palermo; Catania; Cagliari'),

  );
})();
