(function () {
  const q = Trench.q;
  Trench.add('Grab bag',

q('Name a US president',
  'Abraham Lincoln; George Washington; Barack Obama; Donald Trump; Joe Biden; John F. Kennedy/JFK',
  '',
  'Franklin D. Roosevelt/FDR/Franklin Roosevelt/Roosevelt; Theodore Roosevelt/Teddy Roosevelt; Thomas Jefferson; Ronald Reagan; Bill Clinton; George W. Bush/George Bush/Bush/W; Richard Nixon; Harry Truman; Dwight Eisenhower/Ike',
  'James Madison; James Monroe; Andrew Jackson; John Adams/Adams; Ulysses S. Grant; Woodrow Wilson; Jimmy Carter; Gerald Ford; Lyndon B. Johnson/LBJ/Lyndon Johnson/Johnson; William Howard Taft; Herbert Hoover; Calvin Coolidge; Warren G. Harding; James K. Polk; George H. W. Bush/George HW Bush/Bush Sr',
  'James Garfield; William McKinley; Grover Cleveland; Benjamin Harrison/Harrison; Rutherford B. Hayes; Chester Arthur; Zachary Taylor; Martin Van Buren; Millard Fillmore; John Tyler; John Quincy Adams; William Henry Harrison',
  'Franklin Pierce; James Buchanan; Andrew Johnson',
  { names: true }),

q('Name a Shakespeare play',
  'Hamlet; Romeo and Juliet; Macbeth',
  '',
  'Othello; King Lear/Lear; A Midsummer Night\'s Dream/Midsummer Night\'s Dream; The Tempest/Tempest; Julius Caesar; Twelfth Night; Much Ado About Nothing; The Merchant of Venice/Merchant of Venice',
  'As You Like It; Richard III; Henry V; The Taming of the Shrew/Taming of the Shrew; Antony and Cleopatra; Coriolanus; Titus Andronicus; The Winter\'s Tale/Winters Tale',
  'Measure for Measure; Timon of Athens; Cymbeline; Pericles; Troilus and Cressida; Love\'s Labour\'s Lost/Loves Labours Lost; Richard II; Henry IV; King John',
  'The Two Gentlemen of Verona/Two Gentlemen of Verona; The Comedy of Errors/Comedy of Errors; All\'s Well That Ends Well; Henry VI; Henry VIII; The Merry Wives of Windsor/Merry Wives of Windsor; The Two Noble Kinsmen/Two Noble Kinsmen; Edward III'),

q('Name a chess opening or defense',
  'Sicilian Defense/Sicilian; Queen\'s Gambit; Ruy Lopez',
  '',
  'French Defense/French; Caro-Kann; King\'s Indian/King\'s Indian Defense; Italian Game; English Opening/English; Queen\'s Gambit Declined; Queen\'s Gambit Accepted; London System',
  'Nimzo-Indian; Scandinavian; Pirc; Slav; Grunfeld; Dutch Defense/Dutch; Alekhine\'s Defense/Alekhine; Catalan; Benoni; Scotch Game/Scotch; Vienna Game; Petrov\'s Defense/Petroff/Petrov; King\'s Gambit; Evans Gambit; Giuoco Piano; Two Knights',
  'Benko Gambit; Budapest Gambit; Bird\'s Opening/Bird; Owen\'s Defense; Englund Gambit; Danish Gambit; Trompowsky Attack/Trompowsky; Modern Defense; Philidor Defense/Philidor; Max Lange Attack; Fried Liver Attack; Colle System; Reti Opening/Reti; Larsen\'s Opening; Smith-Morra Gambit; Marshall Attack; Najdorf; Dragon; Sveshnikov; Taimanov; Scheveningen',
  'Grob; Orangutan; Sokolsky; Bongcloud; Hippopotamus; Latvian Gambit; Elephant Gambit; Albin Countergambit; Blackmar-Diemer Gambit; Stonewall Attack; Torre Attack; Veresov; Alapin; Vienna Gambit; Halloween Gambit; Frankenstein-Dracula; Belgrade Gambit; Urusov Gambit; Jerome Gambit; Wing Gambit; Icelandic Gambit; Nimzowitsch Defense; St. George Defense; Portuguese Opening; Polish Opening; Hungarian Opening'),

q('Name a car brand',
  'Ford; Toyota; Honda; Chevrolet/Chevy; Tesla; BMW; Mercedes-Benz/Mercedes; Audi; Volkswagen/VW',
  '',
  'Nissan; Hyundai; Kia; Dodge; Jeep; Subaru; Mazda; Lexus; Porsche; Ferrari; Lamborghini; Volvo; Cadillac; Buick; Chrysler; GMC',
  'Acura; Infiniti; Lincoln; Mini; Fiat; Alfa Romeo; Maserati; Jaguar; Land Rover; Range Rover; Bentley; Rolls-Royce; Aston Martin; McLaren; Bugatti; Mitsubishi; Suzuki; Rivian; Lucid; Genesis; Ram; Pontiac; Saturn; Oldsmobile; Mercury; Plymouth; Hummer',
  'Saab; Peugeot; Renault; Citroen; Skoda; Seat; Opel; Vauxhall; Lotus; Pagani; Koenigsegg; Polestar; Fisker; DeLorean; Studebaker; Packard; Hudson; Nash; Tucker; Edsel; Daewoo; Geo; Isuzu; Scion; Daihatsu; Datsun; Smart',
  'Lancia; Abarth; Dacia; Lada; Tata; Mahindra; Geely; BYD; Chery; NIO; Zeekr; Xpeng; Great Wall; Holden; Proton; Perodua; SsangYong; Spyker; Morgan; TVR; Caterham; Noble; Ariel; Ginetta; Bristol; Reliant; Trabant; Wartburg; Zastava; Yugo; Tatra; Maybach; Duesenberg; Auburn; Cord; Pierce-Arrow; Stutz; Willys; Kaiser; Frazer; AMC; Checker; DeSoto; Rambler'),

q('Name a clothing or apparel brand',
  'Nike; Adidas; Gap; Levi\'s/Levis; Zara; H&M; Gucci; Prada; Under Armour',
  '',
  'Puma; Reebok; Champion; Ralph Lauren/Polo; Tommy Hilfiger; Calvin Klein; Lululemon; North Face/The North Face; Patagonia; Uniqlo; Old Navy; Abercrombie/Abercrombie & Fitch; American Eagle; Hollister; Banana Republic; J.Crew/J Crew; Vans; Converse; Louis Vuitton; Chanel; Versace; Burberry; Supreme',
  'Carhartt; Columbia; Brooks Brothers; Vineyard Vines; Lacoste; Fila; Guess; Diesel; Wrangler; Lee; Dockers; Eddie Bauer; L.L.Bean/LL Bean; Arc\'teryx; Canada Goose; Moncler; Hermes; Dior; Fendi; Balenciaga; Givenchy; Armani; Dolce and Gabbana/Dolce & Gabbana; Hugo Boss/Boss; Bonobos; Everlane; Allbirds; Hoka; On; New Balance; Asics; Saucony; Skechers',
  'Pendleton; Filson; Faherty; Johnnie-O; Peter Millar; Southern Tide; Rhone; Vuori; Alo; Fabletics; Gymshark; Fear of God; Off-White; Stussy; Kith; Aime Leon Dore; Todd Snyder; Orvis; Barbour; Aquascutum; Hackett; Ted Baker; Paul Smith; Reiss; Sandro; Maje; Acne Studios; COS; Arket; Salomon; Merrell; Keen; Teva; Birkenstock; Crocs; Dr. Martens/Doc Martens',
  'Loro Piana; Brunello Cucinelli; Zegna; Kiton; Isaia; Canali; Corneliani; Incotex; Orlebar Brown; Sunspel; Drake\'s; Turnbull and Asser; Charvet; Thom Browne; Visvim; Kapital; Beams; Nepenthes; Engineered Garments; Noah; Bode; Rowing Blazers; Sid Mashburn; Mack Weldon; Taylor Stitch; Buck Mason; Huckberry; Proper Cloth; Spier and Mackay; Suitsupply; Mr Porter; Ring Jacket; Cucinelli'),

q('Name a board game',
  'Monopoly; Scrabble; Clue/Cluedo; Risk; Chess; Checkers; Sorry; Life/The Game of Life; Connect Four/Connect 4; Candy Land; Battleship; Trouble; Operation; Jenga; Trivial Pursuit; Pictionary',
  'Uno',
  'Catan/Settlers of Catan; Ticket to Ride; Carcassonne; Pandemic; Cranium; Taboo; Scattergories; Boggle; Mouse Trap; Stratego; Backgammon; Othello; Mastermind; Yahtzee; Twister; Apples to Apples; Cards Against Humanity; Codenames; Chutes and Ladders; Guess Who',
  'Azul; Splendor; 7 Wonders; Dominion; Agricola; Terraforming Mars; Wingspan; Scythe; Gloomhaven; Betrayal at House on the Hill; Dixit; Axis and Allies; Diplomacy; Go; Mancala; Parcheesi; Hungry Hungry Hippos; Rummikub; Mahjong; Blokus; Sequence; Kingdomino',
  'Puerto Rico; Power Grid; Twilight Struggle; Brass; Concordia; Root; Everdell; Spirit Island; Arkham Horror; Eldritch Horror; Mysterium; Pandemic Legacy; Cascadia; Patchwork; Hive; Lost Cities; Tigris and Euphrates; Acquire; Crokinole; Talisman; HeroQuest; Small World; King of Tokyo; Love Letter; Sushi Go',
  'Advanced Squad Leader; Cosmic Encounter; Dune; Dune Imperium; Brass Birmingham; Food Chain Magnate; Great Western Trail; Android Netrunner; Orleans; Santorini; Quoridor; Onitama; Tak; Yinsh; Gipf; Abalone; Lines of Action; Hnefatafl; Senet; Royal Game of Ur; Nine Men\'s Morris; Fox and Geese; Mah-Jongg; Shogi; Xiangqi; Hex; Arimaa; Twixt; Cyclades; Kemet'),

q('Name a card game',
  'Poker; Blackjack; Solitaire; Go Fish; Uno; Hearts; Spades; Rummy; War; Texas Hold\'em/Texas Holdem/Hold\'em; Bridge',
  '',
  'Euchre; Crazy Eights; Old Maid; Gin Rummy/Gin; Cribbage; Slapjack; Canasta; Pinochle; Baccarat; Speed; Egyptian Ratscrew; Skip-Bo; Phase 10; Magic: The Gathering/Magic the Gathering; Pokemon; Yu-Gi-Oh',
  'Bullshit/BS/Cheat; President; Spoons; Snap; Pitch; Whist; Oh Hell; Rummy 500; Hand and Foot; Kings in the Corner; Golf; Sheepshead; Skat; Napoleon; Nertz; Pounce; Casino; Scopa; Briscola; Durak; Belote; Tarot; Faro; Pai Gow; Three Card Monte; Omaha; Seven Card Stud/Stud; Five Card Draw/Draw poker; Razz; Klondike; FreeCell; Spider Solitaire',
  'Piquet; Ecarte; Bezique; Loo; Brag; Newmarket; Michigan; Gleek; Ombre; Quadrille; Basset; Pyramid; Tri Peaks; Canfield; Tichu; Wizard; Big Two; Dou Dizhu; Mus; Tute; Jass; Schafkopf; Doppelkopf; Hanafuda; Truc; Tong Its; Pusoy Dos; Mao; Nomic; Fluxx; Dominion; Exploding Kittens; Sushi Go; Love Letter',
  'Tresette; Mighty; Sheng Ji; Brisca; Zwicker; Vira; Sueca; Bisca; Truco; Cucumber; Panguingue; Pan; Poch; Primero; Triomphe; Maw; Gilet; Barbu; Ninety-Nine; Kaluki; Conquian; Tonk; Tien Len; Hanabi; Skyjo; Coup; The Mind'),

q('Name a programming language',
  'Python; Java; JavaScript; C++; C; Ruby',
  '',
  'C#; PHP; Swift; Kotlin; Go/Golang; Rust; TypeScript; SQL; R; MATLAB; Perl; HTML; CSS',
  'Scala; Haskell; Lua; Dart; Objective-C; Assembly; COBOL; Fortran; Pascal; Lisp; Scheme; Clojure; Elixir; Erlang; Bash; PowerShell; VBA; Visual Basic; Julia; Groovy; Prolog',
  'OCaml; F#; Smalltalk; Ada; Forth; APL; Racket; Nim; Crystal; Zig; Haxe; Delphi; Tcl; Awk; Elm; Idris; Coq; Brainfuck; Scratch; PL-I; ALGOL; BASIC; Common Lisp; Solidity; Verilog; VHDL; D',
  'Befunge; Malbolge; Whitespace; LOLCODE; Piet; Chef; INTERCAL; Jai; Odin; Gleam; Pony; Mercury; Oz; Eiffel; Simula; Modula-2; Oberon; Logo; Hack; Raku; Rexx; PL-SQL; Smalltalk-80; J; K; Q; Factor; Joy; Self; Io; Wren; Janet; Fennel; Hy; Carbon; Mojo; Vale; Roc'),

q('Name a famous painter',
  'Pablo Picasso/Picasso; Vincent van Gogh/Van Gogh/Gogh; Leonardo da Vinci/Da Vinci/Leonardo; Claude Monet/Monet; Michelangelo; Rembrandt; Salvador Dali/Dali; Andy Warhol/Warhol',
  '',
  'Henri Matisse/Matisse; Jackson Pollock/Pollock; Pierre-Auguste Renoir/Renoir; Edouard Manet/Manet; Edgar Degas/Degas; Paul Cezanne/Cezanne; Paul Gauguin/Gauguin; Gustav Klimt/Klimt; Edvard Munch/Munch; Mark Rothko/Rothko; Raphael; Sandro Botticelli/Botticelli; Johannes Vermeer/Vermeer; Francisco Goya/Goya; Georgia O\'Keeffe/O\'Keeffe/Okeeffe; Edward Hopper/Hopper; Frida Kahlo/Kahlo; Banksy; Jean-Michel Basquiat/Basquiat; Piet Mondrian/Mondrian; Rene Magritte/Magritte; J.M.W. Turner/Turner; John Constable/Constable',
  'Caravaggio; Titian; Diego Velazquez/Velazquez; El Greco; Peter Paul Rubens/Rubens; Hieronymus Bosch/Bosch; Pieter Bruegel/Bruegel/Brueghel; Albrecht Durer/Durer; Hans Holbein/Holbein; Frans Hals/Hals; Georges Seurat/Seurat; Camille Pissarro/Pissarro; Alfred Sisley/Sisley; Henri de Toulouse-Lautrec/Toulouse-Lautrec; Marc Chagall/Chagall; Wassily Kandinsky/Kandinsky; Paul Klee/Klee; Joan Miro/Miro; Diego Rivera/Rivera; Francis Bacon; Lucian Freud; David Hockney/Hockney; Roy Lichtenstein/Lichtenstein; Jasper Johns; Robert Rauschenberg/Rauschenberg; Keith Haring/Haring; Jeff Koons/Koons; James McNeill Whistler/Whistler; John Singer Sargent/Sargent; Mary Cassatt/Cassatt; Winslow Homer/Homer; Andrew Wyeth/Wyeth; Norman Rockwell/Rockwell',
  'Giotto; Masaccio; Fra Angelico; Paolo Uccello/Uccello; Piero della Francesca; Andrea Mantegna/Mantegna; Giovanni Bellini; Giorgione; Tintoretto; Paolo Veronese/Veronese; Correggio; Bronzino; Pontormo; Parmigianino; Nicolas Poussin/Poussin; Claude Lorrain; Antoine Watteau/Watteau; Jean-Honore Fragonard/Fragonard; Francois Boucher/Boucher; Jacques-Louis David; Jean-Auguste-Dominique Ingres/Ingres; Eugene Delacroix/Delacroix; Theodore Gericault/Gericault; Gustave Courbet/Courbet; Jean-Francois Millet/Millet; Camille Corot/Corot; Honore Daumier/Daumier; Caspar David Friedrich/Friedrich',
  'Albrecht Altdorfer/Altdorfer; Matthias Grunewald/Grunewald; Lucas Cranach/Cranach; Hans Memling/Memling; Jan van Eyck/Van Eyck; Rogier van der Weyden; Robert Campin; Joachim Patinir; Giuseppe Arcimboldo/Arcimboldo; Francisco de Zurbaran/Zurbaran; Bartolome Esteban Murillo/Murillo; Jusepe de Ribera/Ribera; Jacob van Ruisdael/Ruisdael; Jan Steen; Pieter de Hooch; Carel Fabritius; Thomas Gainsborough/Gainsborough; Joshua Reynolds/Reynolds; William Hogarth/Hogarth; George Stubbs/Stubbs; William Blake/Blake; Thomas Lawrence; Henry Fuseli/Fuseli; Samuel Palmer'),

q('Name a Roman emperor',
  'Augustus; Nero; Caligula; Constantine; Marcus Aurelius; Trajan; Hadrian; Claudius; Tiberius',
  'Julius Caesar/Caesar',
  'Commodus; Vespasian; Titus; Domitian; Nerva; Antoninus Pius; Septimius Severus; Diocletian; Justinian; Julian; Theodosius; Caracalla; Vitellius; Galba; Otho',
  'Lucius Verus; Pertinax; Didius Julianus; Macrinus; Elagabalus; Severus Alexander; Maximinus Thrax; Gordian III; Philip the Arab; Decius; Valerian; Gallienus; Aurelian; Probus; Carus; Maximian; Galerius; Constantius; Licinius; Valens; Valentinian; Gratian; Romulus Augustulus; Zeno; Honorius',
  'Claudius II; Tacitus; Numerian; Carinus; Maxentius; Jovian; Magnentius; Procopius; Avitus; Majorian; Anthemius; Olybrius; Glycerius; Julius Nepos; Libius Severus; Petronius Maximus; Anastasius; Arcadius; Marcian; Leo I; Basiliscus; Heraclius; Tiberius II; Maurice; Phocas; Constans II; Justin I; Justin II',
  'Florianus; Hostilian; Trebonianus Gallus; Aemilian; Pupienus; Balbinus; Gordian I; Gordian II; Eugenius'),

q('Name a famous battle',
  'Gettysburg; Waterloo; Normandy/D-Day; Pearl Harbor; Hastings; Bunker Hill; Alamo',
  '',
  'Thermopylae; Marathon; Trafalgar; Stalingrad; Midway; Battle of the Bulge/Bulge; Antietam; Yorktown; Saratoga; Lexington and Concord/Lexington; Agincourt; Verdun; Somme; Iwo Jima; Okinawa; Dunkirk; Little Bighorn; Bull Run',
  'Tours; Lepanto; Actium; Cannae; Zama; Gaugamela; Salamis; Plataea; Austerlitz; Borodino; Leipzig; Jutland; Battle of Britain/Britain; El Alamein; Kursk; Guadalcanal; Inchon; Dien Bien Phu; Tet Offensive/Tet; Fredericksburg; Chancellorsville; Shiloh; Vicksburg; Chickamauga; Bosworth; Crecy; Poitiers; Culloden',
  'Navarino; Plassey; Rorke\'s Drift; Isandlwana; Tsushima; Mukden; Manzikert; Kosovo; Mohacs; Poltava; Blenheim; Ramillies; Malplaquet; Rocroi; Lutzen; White Mountain; Naseby; Marston Moor; Edgehill; Sedgemoor; Bannockburn; Stirling Bridge; Flodden; Towton; Tewkesbury; Barnet; Hattin; Ain Jalut; Kalka River; Legnica; Mohi; Talas; Red Cliffs',
  'Plains of Abraham; Lake Erie; New Orleans; Tippecanoe; Fallen Timbers; Cowpens; Kings Mountain; Brandywine; Monmouth; Princeton; Trenton; Camden; Guilford Courthouse; Changping; Guandu; Fei River; Teutoburg Forest; Adrianople; Chalons; Catalaunian Plains; Stamford Bridge; Lechfeld; Legnano; Bouvines; Courtrai; Sluys; Nicopolis; Varna; Ankara; Chaldiran; Preveza; Djerba; Malta; Zenta; Narva; Lesnaya; Fleurus'),

q('Name something you might find in a toolbox',
  'Hammer; Screwdriver; Wrench; Pliers; Tape measure; Saw; Nails; Screws',
  '',
  'Level; Drill; Utility knife; Allen key/Hex key; Hacksaw; Chisel; Socket set; Flashlight; Duct tape; Sandpaper; Stud finder; Wire cutters; Crowbar; Mallet',
  'Vise grips/Locking pliers; Channel locks; Awl; Square; Plane; File; Rasp; Caulk gun; Staple gun; Clamp; Needle nose pliers; Multimeter/Voltage tester; Wire stripper; Pry bar; Putty knife; Plumb bob; Chalk line; Bolts; Nuts; Washers; Anchors; Wood glue; Super glue; Pencil; Safety glasses; Work gloves',
  'Torque wrench; Hole saw; Coping saw; Spokeshave; Reciprocating saw; Tin snips; Bolt cutters; Pipe wrench; Basin wrench; Tap and die; Dowel jig; Marking gauge; Bevel gauge; Feeler gauge; Crimper; Soldering iron; Speed square; Combination square; Framing square; Block plane; Jack plane; Dovetail saw; Japanese saw; Pull saw; Flush cut saw; Nail puller; Cat\'s paw; Wonder bar',
  'Scribe; Center punch; Drift punch; Nail set; Calipers; Micrometer; Try square; Adze; Froe; Drawknife; Pin punch; Scratch awl; Trammel points; Marking knife; Cabinet scraper; Card scraper; Burnisher; Auger bit; Brace; Bit brace; Hand drill; Eggbeater drill; Breast drill; Push drill; Yankee screwdriver; Spirit level; Winding sticks; Shooting board; Mitre box; Bench hook'),

q('Name a word that starts with Q',
  'Queen; Question; Quick; Quiet; Quit',
  '',
  'Quarter; Queue; Quote; Quality; Quantity; Quest; Quilt; Quiz',
  'Quasar; Quartz; Quail; Quaint; Quarry; Quiver; Quirk; Quill; Quench; Quibble; Quorum; Quack; Quake; Qualify; Quarrel; Quart; Quarterback; Quartet; Quarantine; Queasy; Quell; Query; Quicksand; Quid; Quip; Quirky; Quota; Quotation',
  'Quagmire; Quixotic; Quintessential; Quandary; Quatrain; Quinoa; Quokka; Quetzal; Quahog; Quasi; Quaver; Queer; Quoth; Quince; Quintet; Quintuplet; Quadruple; Quadruplet; Quadrant; Quadrangle; Quadriceps; Quadrillion; Quartile; Quartermaster; Quiche; Quilting; Quicklime; Quicksilver; Quarterly',
  'Quidnunc; Quoit; Quaff; Quadrille; Querulous; Quiescent; Quisling; Quincunx; Quodlibet; Quotidian; Quoll; Quillwort; Quercine; Quattrocento; Quinquennial; Quinquagenarian; Quincentennial; Quaestor; Quagga; Quaker; Quadrivium; Qibla; Qanat; Qwerty'),

  );
})();
