(function () {
  const q = Trench.q;
  Trench.add('Grab bag',

q('Name a musical instrument',
  'Piano; Guitar; Drums; Violin; Flute; Trumpet; Saxophone',
  '',
  'Cello; Clarinet; Trombone; Harp; Bass guitar/Bass; Harmonica; Accordion; Banjo; Ukulele; Tuba; Oboe; Bagpipes; Xylophone; Triangle; Tambourine; Organ; Keyboard; Synthesizer',
  'Bassoon; Viola; Double bass/Upright bass; French horn/Horn; Piccolo; Mandolin; Sitar; Harpsichord; Marimba; Vibraphone; Glockenspiel; Cymbals; Timpani; Cowbell; Maracas; Castanets; Recorder; Kazoo; Didgeridoo; Bongos; Congas; Cajon; Steel drum; Dulcimer; Zither; Lute; Theremin; Melodica; Pan flute; Ocarina; Tin whistle; Cornet; Flugelhorn; Euphonium; Harmonium',
  'English horn; Contrabassoon; Bass clarinet; Sousaphone; Mellophone; Oud; Bouzouki; Balalaika; Koto; Shamisen; Erhu; Pipa; Guzheng; Shakuhachi; Tabla; Sarod; Santoor; Veena; Kora; Mbira; Djembe; Balafon; Hurdy-gurdy; Nyckelharpa; Viola da gamba; Rebec; Crumhorn; Sackbut; Serpent; Ondes Martenot; Glass harmonica; Hang drum; Handpan; Cavaquinho; Charango; Cuatro; Bandoneon; Concertina',
  'Gamelan; Angklung; Gender; Rebab; Suling; Kantele; Jouhikko; Talharpa; Gadulka; Kaval; Gaida; Duduk; Zurna; Saz; Baglama; Kemenche; Ney; Kanun; Santur; Tar; Setar; Daf; Tombak; Rubab; Dombra; Komuz; Morin khuur; Igil; Khomus; Jew\'s harp; Hardanger fiddle; Tagelharpa; Cittern; Theorbo; Archlute; Chitarrone; Viol; Lirone; Cornett; Shawm; Racket; Dulcian; Rauschpfeife; Bladder pipe'),

q('Name a Greek or Roman god or goddess',
  'Zeus; Poseidon; Hades; Apollo; Athena; Aphrodite; Ares; Hermes; Hera; Jupiter; Mars; Venus; Neptune; Mercury',
  '',
  'Artemis; Dionysus; Demeter; Hephaestus; Persephone; Hestia; Eros; Pan; Cronus; Juno; Minerva; Diana; Vulcan; Cupid; Saturn; Pluto; Bacchus; Ceres; Vesta; Hercules',
  'Nike; Hecate; Helios; Selene; Eos; Nemesis; Morpheus; Hypnos; Thanatos; Iris; Hebe; Themis; Gaia; Uranus; Rhea; Atlas; Prometheus; Janus; Aurora; Luna; Sol; Fortuna; Victoria; Flora; Faunus; Bellona; Somnus; Mors; Terra; Tellus; Ops; Vertumnus; Pomona; Orpheus; Tyche; Triton; Nereus; Oceanus',
  'Hyperion; Theia; Coeus; Crius; Iapetus; Mnemosyne; Phoebe; Tethys; Metis; Leto; Asteria; Eris; Hemera; Nyx; Erebus; Chaos; Tartarus; Aether; Pontus; Thalassa; Hygieia; Asclepius; Aristaeus; Priapus; Momus; Eileithyia; Enyo; Phobos; Deimos; Harmonia; Adrasteia; Bia; Kratos; Zelus; Peitho; Dike; Eunomia; Eirene; Aglaea; Euphrosyne; Thalia',
  'Inuus; Mutunus Tutunus; Sterculius; Cloacina; Crepitus; Fornax; Limentinus; Cardea; Forculus; Janitrix; Tutilina; Robigus; Vitumnus; Sentinus; Orbona; Rumina; Cunina; Levana; Vaticanus; Fabulinus; Edusa; Potina; Statilinus; Nundina; Domiduca; Mena; Iterduca; Adeona; Abeona; Camenae; Egeria; Carmenta; Postverta; Antevorta; Parca; Nona; Decima; Morta; Fama; Pax; Concordia; Spes; Salus; Libertas; Honos; Virtus; Pietas; Clementia'),

q('Name a Star Wars character',
  'Luke Skywalker/Luke; Darth Vader/Vader; Han Solo/Han; Princess Leia/Leia; Yoda; Obi-Wan Kenobi/Obi-Wan/Kenobi; Chewbacca/Chewie; R2-D2/R2D2; C-3PO/C3PO; Emperor Palpatine/Palpatine',
  '',
  'Anakin Skywalker/Anakin; Padme Amidala/Padme; Lando Calrissian/Lando; Boba Fett; Jabba the Hutt/Jabba; Darth Maul/Maul; Mace Windu; Qui-Gon Jinn/Qui-Gon; Count Dooku/Dooku; General Grievous/Grievous; Rey; Kylo Ren; Finn; Poe Dameron/Poe; BB-8; Jar Jar Binks/Jar Jar; The Mandalorian/Mando/Din Djarin; Grogu/Baby Yoda; Ahsoka Tano/Ahsoka; Greedo; Wedge Antilles/Wedge',
  'Admiral Ackbar/Ackbar; Grand Moff Tarkin/Tarkin; Bib Fortuna; Salacious Crumb; Nien Nunb; Wicket; Max Rebo; Sy Snootles; Watto; Captain Panaka; Shmi Skywalker; Cliegg Lars; Owen Lars; Beru Lars; Biggs Darklighter/Biggs; Admiral Piett/Piett; Captain Phasma/Phasma; General Hux/Hux; Snoke; Maz Kanata; Jyn Erso; Cassian Andor/Andor; K-2SO; Chirrut Imwe; Baze Malbus; Saw Gerrera; Bodhi Rook; Orson Krennic/Krennic; Thrawn; Ezra Bridger; Kanan Jarrus; Hera Syndulla; Sabine Wren; Zeb; Chopper; Cad Bane; Asajj Ventress/Ventress; Savage Opress; Hondo Ohnaka; Fennec Shand; Cara Dune; Moff Gideon; IG-88; Bossk; Dengar; 4-LOM; Zuckuss',
  'Dexter Jettster; Zam Wesell; Jango Fett; Nute Gunray; Rune Haako; Wat Tambor; Poggle the Lesser; Shaak Ti; Plo Koon; Kit Fisto; Ki-Adi-Mundi; Aayla Secura; Luminara Unduli; Barriss Offee; Saesee Tiin; Even Piell; Yarael Poof; Oppo Rancisis; Adi Gallia; Eeth Koth; Depa Billaba; Stass Allie; Bail Organa; Mon Mothma; Jan Dodonna; Garven Dreis; Rieekan; Crix Madine; Lobot; Ugnaught; Oola; Ponda Baba; Dr. Evazan; Figrin D\'an; Momaw Nadon; Lak Sivrak; Kitik Keed\'kak; Garindan; Wuher; Chalmun',
  'Rotta; Gardulla; Ysanne Isard; Tycho Celchu; Corran Horn; Mara Jade; Jacen Solo; Jaina Solo; Anakin Solo; Kyle Katarn; Talon Karrde; Ben Skywalker; Cade Skywalker; Revan; Bastila Shan; Darth Malak; Darth Nihilus; Darth Sion; Darth Traya; Kreia; Carth Onasi; Canderous Ordo; HK-47; T3-M4; Mission Vandrell; Zaalbar; Juhani; Jolee Bindo; Visas Marr; Atton Rand; Mira; Hanharr; Bao-Dur; Disciple; Brianna; Mandalore'),

q('Name a Pokemon',
  'Pikachu; Charizard; Bulbasaur; Squirtle; Charmander; Eevee; Mewtwo; Mew; Jigglypuff; Snorlax',
  '',
  'Psyduck; Gengar; Meowth; Magikarp; Gyarados; Lucario; Togepi; Ditto; Vulpix; Onix; Pidgey; Rattata; Machop; Geodude; Ekans; Arcanine; Dragonite; Lapras; Blastoise; Venusaur; Raichu; Wobbuffet; Piplup; Mudkip; Greninja; Zubat; Abra; Slowpoke; Cubone; Marowak; Lugia; Ho-Oh; Rayquaza',
  'Umbreon; Espeon; Vaporeon; Jolteon; Flareon; Leafeon; Glaceon; Sylveon; Gardevoir; Blaziken; Sceptile; Swampert; Garchomp; Infernape; Torchic; Treecko; Chimchar; Turtwig; Shinx; Riolu; Zorua; Zoroark; Absol; Metagross; Salamence; Tyranitar; Scizor; Heracross; Gliscor; Mimikyu; Rowlet; Litten; Popplio; Dedenne; Pichu; Cleffa; Togekiss; Mr. Mime; Chansey; Blissey; Kangaskhan; Scyther; Pinsir; Tauros; Aerodactyl; Moltres; Zapdos; Articuno; Dratini; Dragonair; Bellsprout; Oddish; Gloom; Vileplume; Paras; Venonat; Diglett; Dugtrio; Poliwag; Poliwhirl; Poliwrath; Tentacool; Tentacruel; Ponyta; Rapidash; Slowbro; Farfetch\'d; Doduo; Dodrio; Seel; Dewgong; Grimer; Muk; Shellder; Cloyster; Gastly; Haunter; Drowzee; Hypno; Krabby; Kingler; Voltorb; Electrode; Exeggcute; Exeggutor; Lickitung; Koffing; Weezing; Rhyhorn; Rhydon; Horsea; Seadra; Goldeen; Seaking; Staryu; Starmie',
  'Spiritomb; Rotom; Bidoof; Kricketot; Burmy; Wormadam; Combee; Buizel; Floatzel; Cherubi; Shellos; Gastrodon; Drifloon; Drifblim; Buneary; Lopunny; Glameow; Purugly; Stunky; Skuntank; Bronzor; Bronzong; Bonsly; Mime Jr.; Happiny; Chatot; Munchlax; Hippopotas; Hippowdon; Skorupi; Drapion; Croagunk; Toxicroak; Carnivine; Finneon; Lumineon; Mantyke; Snover; Abomasnow; Weavile; Magnezone; Lickilicky; Rhyperior; Tangrowth; Electivire; Magmortar; Mamoswine; Porygon-Z; Gallade; Probopass; Dusknoir; Froslass; Uxie; Mesprit; Azelf; Dialga; Palkia; Heatran; Regigigas; Giratina; Cresselia; Phione; Manaphy; Darkrai; Shaymin; Arceus',
  'Wishiwashi; Bruxish; Minior; Komala; Turtonator; Togedemaru; Drampa; Dhelmise; Jangmo-o; Hakamo-o; Kommo-o; Bounsweet; Steenee; Tsareena; Comfey; Oranguru; Passimian; Sandygast; Palossand; Pyukumuku; Type: Null; Silvally; Cosmog; Cosmoem; Solgaleo; Lunala; Necrozma; Magearna; Marshadow; Poipole; Naganadel; Stakataka; Blacephalon; Zeraora; Meltan; Melmetal; Grookey; Scorbunny; Sobble; Skwovet; Greedent; Rookidee; Corvisquire; Corviknight; Blipbug; Dottler; Orbeetle; Nickit; Thievul; Gossifleur; Eldegoss; Wooloo; Dubwool; Chewtle; Drednaw; Yamper; Boltund; Rolycoly; Carkol; Coalossal; Applin; Flapple; Appletun; Silicobra; Sandaconda; Cramorant; Arrokuda; Barraskewda; Toxel; Toxtricity; Sizzlipede; Centiskorch; Clobbopus; Grapploct; Sinistea; Polteageist; Hatenna; Hattrem; Hatterene; Impidimp; Morgrem; Grimmsnarl; Obstagoon; Perrserker; Cursola; Sirfetch\'d; Mr. Rime; Runerigus; Milcery; Alcremie; Falinks; Pincurchin; Snom; Frosmoth; Stonjourner; Eiscue; Indeedee; Morpeko; Cufant; Copperajah; Dracozolt; Arctozolt; Dracovish; Arctovish; Duraludon; Dreepy; Drakloak; Dragapult; Zacian; Zamazenta; Eternatus; Kubfu; Urshifu; Zarude; Regieleki; Regidrago; Glastrier; Spectrier; Calyrex'),

q('Name a Simpsons character',
  'Homer; Marge; Bart; Lisa; Maggie; Ned Flanders/Flanders; Mr. Burns/Burns; Moe',
  '',
  'Milhouse; Apu; Krusty; Barney; Principal Skinner/Skinner; Ralph Wiggum/Ralph; Chief Wiggum/Wiggum; Nelson; Comic Book Guy; Groundskeeper Willie/Willie; Grampa/Abe Simpson; Smithers; Sideshow Bob; Reverend Lovejoy/Lovejoy; Patty; Selma; Lenny; Carl; Santa\'s Little Helper; Snowball',
  'Edna Krabappel/Krabappel; Otto; Dr. Hibbert/Hibbert; Dr. Nick; Professor Frink/Frink; Troy McClure; Lionel Hutz; Kent Brockman/Brockman; Mayor Quimby/Quimby; Fat Tony; Cletus; Rod Flanders; Todd Flanders; Maude Flanders/Maude; Martin Prince/Martin; Jimbo; Dolph; Kearney; Sherri; Terri; Janey; Database; Superintendent Chalmers/Chalmers; Lunchlady Doris; Disco Stu; Hans Moleman; Gil; Duffman; Rainier Wolfcastle; McBain; Itchy; Scratchy; Mr. Teeny; Mona; Herb; Kang; Kodos; Jasper; Agnes Skinner; Sea Captain',
  'Bumblebee Man; Blue-Haired Lawyer; Squeaky-Voiced Teen; Cookie Kwan; Crazy Cat Lady; Old Jewish Man; Eddie; Lou; Luann Van Houten; Kirk Van Houten; Brandine; Uter; Lewis; Wendell; Allison Taylor; Richard; Jessica Lovejoy; Mrs. Lovejoy/Helen Lovejoy; Akira; Dr. Marvin Monroe; Dr. Zweig; Artie Ziff; Rich Texan; Poochie; Capital City Goofball; Mr. Largo; Princess Kashmir; Lindsey Naegle; Hank Scorpio; Frank Grimes/Grimey; Mindy Simmons; Stampy; Waylon; Jacqueline Bouvier; Ling Bouvier; Spider Pig/Plopper; Pin Pals; Bleeding Gums Murphy; Mr. Bergstrom; Lurleen Lumpkin; Becky; Shary Bobbins; Fallout Boy; Radioactive Man; Hugh Parkfield',
  'Cecil Terwilliger; Francesca Terwilliger; Calliope; Gunter; Ernst; Hubert Wong; Kumiko Albertson; Colby Krause; Benjamin; Doug; Gary; Dr. Colossus; Uter Zorker; Ruth Powers; Laura Powers; Zia; Roger Meyers Jr.; Luigi Risotto/Luigi; Bernice Hibbert; Gabbo; Mr. Sparkle; Black Widower; Number One; Apu Nahasapeemapetilon; Manjula; Sanjay; Pahusacheta; Gheet; Anoop; Nikhil; Uma; Poonam; Jub-Jub'),

q('Name a vegetable',
  'Carrot; Broccoli; Potato; Tomato; Onion; Corn; Lettuce; Spinach; Cucumber; Celery',
  '',
  'Peas; Green beans; Cauliflower; Cabbage; Bell pepper/Pepper; Zucchini; Asparagus; Sweet potato; Mushroom; Garlic; Kale; Eggplant; Squash; Pumpkin; Radish; Beet; Brussels sprouts; Artichoke; Avocado',
  'Turnip; Parsnip; Rutabaga; Leek; Shallot; Scallion/Green onion; Fennel; Kohlrabi; Okra; Bok choy; Collard greens/Collards; Swiss chard/Chard; Arugula; Endive; Radicchio; Watercress; Bean sprouts; Snow peas; Snap peas; Jicama; Daikon; Yam; Cassava; Taro; Butternut squash; Acorn squash; Spaghetti squash; Rhubarb; Jalapeno; Habanero; Edamame; Lima beans; Romaine',
  'Celeriac; Salsify; Sunchoke/Jerusalem artichoke; Burdock; Horseradish; Lotus root; Water chestnut; Bamboo shoots; Fiddlehead; Ramp; Nopales; Tomatillo; Chayote; Bitter melon; Winter melon; Napa cabbage; Savoy cabbage; Red cabbage; Romanesco; Broccolini; Broccoli rabe/Rapini; Mizuna; Tatsoi; Komatsuna; Mustard greens; Dandelion greens; Purslane; Sorrel; Cardoon; Mache; Frisee; Escarole; Treviso; Kalettes; Yardlong beans; Fava beans; Cranberry beans; Black-eyed peas; Pattypan; Delicata; Kabocha; Calabaza; Hubbard squash; Cipollini; Pearl onion; Spring onion; Sweet corn',
  'Skirret; Oca; Ulluco; Mashua; Yacon; Arracacha; Maca; Chicory root; Dandelion root; Samphire; Sea beans; Glasswort; Sea kale; Orache; Good King Henry; Lamb\'s quarters; Nettle; Ground elder; Alexanders; Rocambole; Ostrich fern; Hostas; Daylily buds; Squash blossoms; Zucchini flowers; Nasturtium leaves; Borage leaves; Chrysanthemum greens; Shungiku; Water spinach; Kangkong; Amaranth greens; Callaloo; Malabar spinach; Molokhia; Jute leaves; Ugu; Pumpkin leaves; Cassava leaves; Taro leaves; Sweet potato leaves; Moringa leaves'),

q('Name a Broadway musical',
  'Hamilton; Wicked; The Lion King/Lion King; Cats; Phantom of the Opera/The Phantom of the Opera; Les Miserables/Les Mis; Chicago; Grease; Rent',
  '',
  'West Side Story; Hello Dolly; Oklahoma; The Sound of Music/Sound of Music; Fiddler on the Roof; Mamma Mia; Book of Mormon/The Book of Mormon; Dear Evan Hansen; Annie; A Chorus Line; Cabaret; Jersey Boys; Kinky Boots; Matilda; Newsies; Aladdin; Frozen; Waitress; Come From Away; Hadestown; Six; Beetlejuice; Mean Girls; Moulin Rouge; Into the Woods; Sweeney Todd; My Fair Lady; Guys and Dolls; The Music Man/Music Man; South Pacific; Kiss Me Kate; Evita; Jesus Christ Superstar; Godspell; Hairspray; Spamalot; The Producers; Avenue Q; Spring Awakening',
  'Anything Goes; Show Boat; Carousel; The King and I/King and I; Gypsy; Funny Girl; Camelot; Man of La Mancha; Pippin; Hair; Company; Follies; Sunday in the Park with George; Assassins; Passion; A Little Night Music; Merrily We Roll Along; Sunset Boulevard; Miss Saigon; Starlight Express; Beauty and the Beast; Footloose; Fame; Dreamgirls; Ragtime; Titanic; Parade; Urinetown; Thoroughly Modern Millie; Aida; Memphis; Once; Fun Home; Kimberly Akimbo; Hell\'s Kitchen; Heathers; Be More Chill; Falsettos; Next to Normal; In the Heights; Bring It On; Legally Blonde; Shrek; Billy Elliot; School of Rock; Tootsie; Anastasia; Escape to Margaritaville; Ain\'t Too Proud; Girl from the North Country',
  'Bat Boy; Violet; Floyd Collins; Side Show; Caroline or Change; Grey Gardens; The Light in the Piazza; Lestat; Bonnie and Clyde; Catch Me If You Can; Xanadu; Rock of Ages; Ghost; Leap of Faith; Scandalous; Lysistrata Jones; Chaplin; Big Fish; Rocky; Hands on a Hardbody; Soul Doctor; Giant; Amelie; Bandstand; Groundhog Day; Prince of Broadway; Summer; Oh Hello; Mrs. Doubtfire; Diana; Paradise Square; Tina; Jagged Little Pill; The Notebook; Back to the Future; Suffs; Water for Elephants; Illinoise; The Outsiders; Shucked; Some Like It Hot; Lempicka; Dogfight; Natasha Pierre and the Great Comet of 1812; Great Comet; Fiorello; Bloomer Girl; Pal Joey; On Your Toes; Babes in Arms; Lady in the Dark; One Touch of Venus; Brigadoon; Paint Your Wagon; Finian\'s Rainbow',
  ''),

  );
})();
