(function () {
  const q = Trench.q;
  Trench.add('Nature & science',

q('Name a chemical element',
  'Hydrogen; Oxygen; Carbon; Gold; Iron; Helium',
  '',
  'Nitrogen; Silver; Sodium; Calcium; Copper; Lead; Zinc; Neon; Chlorine; Aluminum/Aluminium; Mercury; Uranium; Silicon; Potassium; Lithium',
  'Tin; Nickel; Cobalt; Platinum; Argon; Krypton; Xenon; Boron; Magnesium; Phosphorus; Sulfur/Sulphur; Titanium; Tungsten; Fluorine; Iodine; Bromine; Radon; Plutonium',
  'Bismuth; Cadmium; Antimony; Arsenic; Gallium; Germanium; Selenium; Tellurium; Rubidium; Cesium/Caesium; Strontium; Barium; Zirconium; Palladium; Rhodium; Iridium; Osmium; Beryllium; Vanadium; Chromium; Manganese; Molybdenum; Niobium; Scandium; Yttrium; Thallium; Polonium; Radium; Francium; Thorium; Neptunium; Americium',
  'Hafnium; Rhenium; Thulium; Ytterbium; Lutetium; Holmium; Dysprosium; Erbium; Terbium; Europium; Gadolinium; Praseodymium; Neodymium; Samarium; Promethium; Protactinium; Berkelium; Californium; Einsteinium; Fermium; Nobelium; Technetium; Ruthenium; Indium; Astatine; Tantalum; Lanthanum; Cerium; Actinium; Curium; Mendelevium; Lawrencium; Oganesson; Livermorium; Tennessine; Nihonium; Moscovium; Copernicium; Flerovium; Darmstadtium; Roentgenium; Meitnerium; Hassium; Bohrium; Seaborgium; Dubnium; Rutherfordium'),

q('Name an animal you would find in Africa',
  'Lion; Elephant; Giraffe; Zebra; Hippo/Hippopotamus; Rhino/Rhinoceros; Cheetah; Gorilla',
  '',
  'Leopard; Monkey; Crocodile; Gazelle; Hyena; Baboon; Chimpanzee; Warthog; Ostrich; Wildebeest/Gnu; Buffalo; Meerkat; Flamingo; Antelope; Lemur',
  'Impala; Springbok; Kudu; Eland; Oryx; Okapi; Aardvark; Mandrill; Colobus; Vervet; Wild dog/African wild dog; Jackal; Caracal; Serval; Mongoose; Honey badger; Pangolin; Secretary bird; Vulture; Marabou stork; Nile crocodile; Black mamba; Chameleon; Gerenuk; Topi; Hartebeest; Waterbuck; Bongo; Dik-dik; Duiker',
  'Aardwolf; Bat-eared fox; Fennec fox; Genet; Civet; Bushbaby; Galago; Potto; Hyrax/Rock hyrax; Elephant shrew; Naked mole rat; Sable antelope; Roan antelope; Nyala; Bushbuck; Sitatunga; Lechwe; Puku; Oribi; Steenbok; Klipspringer; Grysbok; Reedbuck; Saiga; Bontebok; Blesbok; Gemsbok; Pygmy hippo; Forest elephant; Bonobo; Drill; Patas monkey; Gelada; Guereza; Diana monkey; Mangabey',
  'Aye-aye; Fossa; Tenrec; Sifaka; Indri; Zorilla; Striped polecat; Ratel; Cape fox; Side-striped jackal; Ethiopian wolf; Golden cat; African golden wolf; Egyptian mongoose; Slender mongoose; Meller\'s mongoose; Dwarf mongoose; Banded mongoose; Springhare; Cape porcupine; Brush-tailed porcupine; Dassie rat; Mole-rat; Golden mole; Otter shrew; Giant otter shrew; Hammerkop; Shoebill; Saddle-billed stork; Bateleur; Secretarybird; Kori bustard; Lilac-breasted roller; Carmine bee-eater; Hoopoe; Turaco; Hornbill; Ground hornbill; Helmeted guineafowl; Guineafowl'),

q('Name a type of bird',
  'Eagle; Robin; Sparrow; Owl; Penguin; Hawk; Crow; Cardinal; Blue Jay/Bluejay; Duck; Parrot; Pigeon; Seagull/Gull',
  '',
  'Flamingo; Hummingbird; Woodpecker; Swan; Pelican; Peacock; Ostrich; Falcon; Raven; Finch; Goose; Turkey; Chickadee; Heron; Kingfisher; Toucan; Vulture; Stork; Albatross; Cockatoo; Condor; Emu; Chicken',
  'Kiwi; Puffin; Cormorant; Osprey; Crane; Egret; Ibis; Kestrel; Nuthatch; Oriole; Warbler; Wren; Starling; Swallow; Swift; Thrush; Tanager; Bluebird; Bunting; Grouse; Pheasant; Quail; Roadrunner; Sandpiper; Loon; Magpie; Mockingbird; Meadowlark; Dove; Macaw; Parakeet; Budgie; Canary; Lovebird; Cockatiel; Mallard; Pintail; Teal; Canvasback; Kookaburra; Lyrebird',
  'Bittern; Curlew; Dipper; Dunlin; Gannet; Grebe; Harrier; Hoopoe; Jacana; Kite; Lapwing; Merganser; Nightjar; Plover; Rail; Shrike; Skua; Spoonbill; Tern; Trogon; Turnstone; Whimbrel; Yellowhammer; Bee-eater; Hornbill; Cassowary; Kakapo; Kea; Quetzal; Rhea; Whip-poor-will; Nighthawk; Killdeer; Avocet; Oystercatcher; Phalarope; Godwit; Snipe; Woodcock; Ptarmigan; Capercaillie; Lark; Pipit; Wagtail; Waxwing; Vireo; Junco; Towhee; Phoebe; Grosbeak; Crossbill; Siskin; Redpoll; Linnet; Goldfinch; Chaffinch; Bullfinch',
  'Shoebill; Hoatzin; Secretarybird; Frogmouth; Bowerbird; Oilbird; Tody; Motmot; Potoo; Kagu; Takahe; Weka; Tinamou; Screamer; Sunbittern; Limpkin; Harpy eagle; Boobook; Sungrebe; Finfoot; Seriema; Cuckoo-roller; Mesite; Plains-wanderer; Hamerkop; Ground hornbill; Lilac-breasted roller; Fairywren; Honeyeater; Pardalote; Thornbill; Treecreeper; Babbler; Drongo; Fantail; Monarch flycatcher; Cotinga; Manakin; Antbird; Ovenbird; Woodcreeper; Tapaculo; Gnatcatcher; Verdin; Bushtit; Titmouse; Kinglet; Dickcissel; Bobolink; Ani; Anhinga; Frigatebird; Tropicbird; Booby; Petrel; Shearwater; Fulmar; Prion'),

q('Name a type of tree',
  'Oak; Maple; Pine; Birch; Palm; Willow; Elm; Cedar; Redwood',
  '',
  'Spruce; Fir; Ash; Beech; Cherry; Apple; Poplar; Cypress; Sequoia; Magnolia; Dogwood; Hickory; Walnut; Eucalyptus; Aspen; Hemlock; Sycamore; Baobab',
  'Sassafras; Hawthorn; Larch; Linden; Alder; Hornbeam; Juniper; Yew; Holly; Mahogany; Teak; Ebony; Banyan; Mulberry; Chestnut; Buckeye; Basswood; Tamarack; Locust; Ginkgo/Gingko; Joshua tree; Mangrove; Olive; Fig; Acacia; Pecan; Peach; Pear; Lemon tree; Orange tree; Bamboo; Cottonwood; Black walnut; Douglas fir',
  'Sweetgum; Tupelo; Catalpa; Hackberry; Boxelder; Osage orange; Paulownia; Rowan; Whitebeam; Wych elm; Plane; Tulip tree/Tulip poplar; Kapok; Neem; Jacaranda; Bristlecone pine; Monkey puzzle; Dragon blood tree; Cork oak; Lignum vitae; Ironwood; Redbud; Serviceberry; Sourwood; Persimmon; Pawpaw; Mimosa; Silver maple; Sugar maple; Red maple; Norway maple; Japanese maple; Live oak; White oak; Red oak; Pin oak; Bur oak; Scrub oak; Paper birch; River birch; Weeping willow; Pussy willow',
  'Balsa; Rosewood; Sandalwood; Wollemi pine; Kauri; Totara; Rimu; Pohutukawa; Quiver tree; Cassia; Fever tree; Witch hazel; Smoke tree; Franklinia; Dawn redwood; Sugi; Hinoki; Cryptomeria; Metasequoia; Araucaria; Norfolk pine; Cedar of Lebanon; Atlas cedar; Deodar; Stone pine; Maritime pine; Aleppo pine; Scots pine; Lodgepole pine; Ponderosa pine; Sugar pine; Pitch pine; Longleaf pine; Loblolly pine; Slash pine; Shortleaf pine; Jack pine; Red pine; White pine; Limber pine; Whitebark pine; Foxtail pine; Torrey pine; Coulter pine; Digger pine; Knobcone pine'),

q('Name a flower',
  'Rose; Tulip; Daisy; Sunflower; Lily; Orchid; Daffodil',
  '',
  'Carnation; Violet; Lavender; Marigold; Poppy; Peony; Iris; Lilac; Hydrangea; Dandelion; Jasmine; Lotus; Pansy; Petunia; Geranium',
  'Zinnia; Dahlia; Chrysanthemum; Hibiscus; Begonia; Snapdragon; Cosmos; Foxglove; Lupine/Lupin; Magnolia; Gardenia; Camellia; Azalea; Anemone; Aster; Buttercup; Bluebell; Cornflower; Delphinium; Freesia; Gladiolus; Honeysuckle; Primrose; Sweet pea',
  'Amaryllis; Alstroemeria; Clematis; Columbine; Cyclamen; Forget-me-not; Hollyhock; Impatiens; Larkspur; Morning glory; Nasturtium; Periwinkle; Ranunculus; Statice; Verbena; Wisteria; Yarrow; Protea; Bird of paradise; Plumeria; Edelweiss; Crocus; Hyacinth; Narcissus; Lily of the valley; Baby\'s breath; Black-eyed Susan; Calla lily; Bougainvillea; Gerbera; Oleander',
  'Hellebore; Nigella; Salvia; Scabiosa; Trillium; Trumpet vine; Bleeding heart; Lisianthus; Celosia; Allium; Agapanthus; Anthurium; Cattleya; Heliotrope; Red hot poker; Lobelia; Penstemon; Phlox; Queen Anne\'s lace; Tansy; Veronica; Zantedeschia; Bellflower; Campanula; Coneflower; Echinacea; Coreopsis; Gaillardia; Gaura; Hepatica; Liatris; Monkshood; Aconite; Snowdrop; Squill; Scilla; Fritillaria; Checkered lily; Corydalis; Pasqueflower; Globeflower; Sea holly; Eryngium; Teasel; Thistle; Cardoon; Gentian; Saxifrage; Sedum; Stonecrop; Forsythia'),

q('Name a dinosaur',
  'T. rex/T-rex/Tyrannosaurus/Tyrannosaurus rex; Triceratops; Velociraptor; Stegosaurus; Brachiosaurus',
  'Pterodactyl',
  'Brontosaurus; Diplodocus; Spinosaurus; Ankylosaurus; Allosaurus; Iguanodon; Apatosaurus; Parasaurolophus; Pachycephalosaurus',
  'Gallimimus; Dilophosaurus; Compsognathus; Carnotaurus; Giganotosaurus; Archaeopteryx; Utahraptor; Deinonychus; Baryonyx; Oviraptor; Maiasaura; Edmontosaurus; Argentinosaurus; Coelophysis; Protoceratops; Hadrosaurus; Therizinosaurus; Troodon; Plateosaurus',
  'Albertosaurus; Gorgosaurus; Microraptor; Pachyrhinosaurus; Styracosaurus; Centrosaurus; Corythosaurus; Lambeosaurus; Sauropelta; Nodosaurus; Camarasaurus; Mamenchisaurus; Cryolophosaurus; Herrerasaurus; Eoraptor; Ceratosaurus; Megalosaurus; Torosaurus; Kentrosaurus; Minmi; Sinosauropteryx; Yutyrannus; Dracorex; Stygimoloch; Muttaburrasaurus; Leaellynasaura; Majungasaurus; Suchomimus',
  'Qianzhousaurus; Nigersaurus; Amargasaurus; Masiakasaurus; Irritator; Concavenator; Zuniceratops; Fukuiraptor; Shunosaurus; Opisthocoelicaudia; Bambiraptor; Tarbosaurus; Saltasaurus; Scelidosaurus; Psittacosaurus; Guanlong; Dilong; Limusaurus; Sinornithosaurus; Anchiornis; Epidexipteryx; Caudipteryx; Beipiaosaurus; Deltadromeus; Paralititan; Patagotitan; Dreadnoughtus; Puertasaurus; Futalognkosaurus; Sauroposeidon; Supersaurus; Seismosaurus; Amphicoelias'),

q('Name a type of snake',
  'Cobra; Rattlesnake; Python; Boa constrictor/Boa; Anaconda; Garter snake/Garter; King cobra; Viper; Copperhead',
  '',
  'Black mamba; Coral snake; Cottonmouth/Water moccasin; Corn snake; Kingsnake/King snake; Milk snake; Rat snake; Sea snake; Bull snake; Ball python; Gopher snake; Hognose',
  'Taipan; Bushmaster; Fer-de-lance; Sidewinder; Puff adder; Gaboon viper; Boomslang; Krait; Asp; Adder; Green mamba; Tiger snake; Brown snake; Reticulated python; Burmese python; Rainbow boa; Emerald tree boa; Eastern diamondback; Western diamondback; Diamondback; Timber rattlesnake; Mojave rattlesnake',
  'Racer; Whipsnake; Vine snake; Death adder; Saw-scaled viper; Pit viper; Mamushi; Habu; Lancehead; Terciopelo; Cantil; Indigo snake; Blind snake; Carpet python; Ribbon snake; Glossy snake; Night snake; Coachwhip; Ringneck snake; Rosy boa; Rubber boa; Brown tree snake; Green tree python; Rough green snake; Smooth green snake; Eastern hognose; Western hognose; Eastern indigo; Black racer; Black rat snake; Pine snake; Scarlet snake; Scarlet kingsnake',
  'Sunbeam snake; Mussurana; Wolf snake; Kukri snake; Flying snake; Elephant trunk snake; Mangrove snake; Cat snake; Keelback; Tentacled snake; Mud snake; Rainbow snake; Tiger rattlesnake; Peringuey\'s adder; Horned viper; Desert horned viper; Russell\'s viper; Bamboo viper; Eyelash viper; Palm viper; Jararaca; Urutu; Bothrops; Aspic viper; Nose-horned viper; Ottoman viper; Blunt-nosed viper; Armenian viper; Meadow viper; Orsini\'s viper; Massasauga; Pygmy rattlesnake; Ground rattlesnake; Rock rattlesnake; Twin-spotted rattlesnake; Ridge-nosed rattlesnake'),

q('Name a sea creature',
  'Shark; Whale; Dolphin; Octopus; Jellyfish; Crab; Starfish/Sea star; Seahorse',
  '',
  'Squid; Lobster; Clam; Sea turtle/Turtle; Stingray; Eel; Seal; Sea lion; Orca/Killer whale; Manatee; Narwhal; Walrus; Shrimp; Oyster; Sea urchin/Urchin; Barracuda; Swordfish; Clownfish; Penguin',
  'Manta ray; Hammerhead; Anemone/Sea anemone; Coral; Sponge; Cuttlefish; Nautilus; Krill; Plankton; Barnacle; Sea cucumber; Pufferfish; Moray eel; Angelfish; Lionfish; Marlin; Tuna; Mussel; Scallop; Sea otter; Dugong; Beluga; Great white; Whale shark; Humpback; Blue whale; Sperm whale; Bottlenose dolphin; Porpoise; Snapper; Grouper; Mahi-mahi; Sailfish; Flounder; Halibut',
  'Sea slug/Nudibranch; Remora; Anglerfish; Gulper eel; Hagfish; Lamprey; Sunfish/Mola mola; Oarfish; Blobfish; Isopod; Sea pen; Sea lily; Tubeworm; Siphonophore; Portuguese man o\' war/Man o\' war; Sea angel; Sea butterfly; Moon jelly; Box jelly; Sea hare; Sea snail; Conch; Whelk; Limpet; Abalone; Cowrie; Cone snail; Triton; Hermit crab; Spider crab; Fiddler crab; Horseshoe crab; Stone crab; Dungeness crab; King crab; Snow crab; Blue crab',
  'Vampire squid; Dumbo octopus; Pyrosome; Comb jelly/Ctenophore; Salp; Chiton; Brittle star; Feather star; Giant isopod; Goblin shark; Frilled shark; Cookiecutter shark; Yeti crab; Pistol shrimp; Mantis shrimp; Coconut crab; Sea spider; Leafy sea dragon; Blue dragon; Basket star; Giant squid; Colossal squid; Humboldt squid; Firefly squid; Glass squid; Blanket octopus; Mimic octopus; Blue-ringed octopus; Flamboyant cuttlefish; Bobtail squid; Hawaiian bobtail squid; Barreleye; Fangtooth; Viperfish; Dragonfish; Lanternfish; Hatchetfish; Bristlemouth; Pelican eel; Football fish; Black swallower; Tripod fish; Barrel-eye'),

q('Name a famous scientist',
  'Albert Einstein; Isaac Newton; Charles Darwin; Galileo Galilei/Galileo; Nikola Tesla; Marie Curie/Curie; Stephen Hawking',
  '',
  'Thomas Edison; Louis Pasteur; Michael Faraday; Niels Bohr; Richard Feynman; Nicolaus Copernicus/Copernicus; Johannes Kepler/Kepler; Gregor Mendel; Benjamin Franklin; Carl Sagan; Alan Turing; Ivan Pavlov; Alexander Fleming; Sigmund Freud; Neil deGrasse Tyson',
  'James Clerk Maxwell/Maxwell; Max Planck; Werner Heisenberg; Erwin Schrodinger; J. Robert Oppenheimer/Oppenheimer; Enrico Fermi; Edwin Hubble; Antoine Lavoisier; Dmitri Mendeleev; Alessandro Volta; Georg Ohm; Andre-Marie Ampere; James Joule; Lord Kelvin/William Thomson; Robert Boyle; Robert Hooke; Carl Linnaeus; Antonie van Leeuwenhoek; Ada Lovelace; Grace Hopper; Jane Goodall; Jonas Salk; Edward Jenner; Rosalind Franklin; Francis Crick; James Watson',
  'Paul Dirac; Wolfgang Pauli; Max Born; Ernest Rutherford; J. J. Thomson/JJ Thomson; James Chadwick; Heinrich Hertz; Ludwig Boltzmann; Carl Friedrich Gauss; Leonhard Euler; Bernhard Riemann; Emmy Noether; Srinivasa Ramanujan; Satyendra Nath Bose; C. V. Raman; Subrahmanyan Chandrasekhar; Dorothy Hodgkin; Barbara McClintock; Lise Meitner; George Washington Carver; Charles Lyell; James Hutton; Alfred Wegener; Henry Cavendish; Joseph Priestley; John Dalton; Amedeo Avogadro; Alfred Nobel; Tycho Brahe; Christiaan Huygens; Giovanni Cassini; William Herschel; Caroline Herschel',
  'Joseph von Fraunhofer; Ptolemy; Hipparchus; Eratosthenes; Aristarchus; Ibn al-Haytham/Alhazen; Al-Khwarizmi; Fibonacci; Hypatia; Andreas Vesalius; William Harvey; Luigi Galvani; Arnold Sommerfeld; Vera Rubin; Jocelyn Bell Burnell; Cecilia Payne-Gaposchkin; Henrietta Leavitt; Annie Jump Cannon; Hans Geiger; Wilhelm Rontgen; Henri Becquerel; Pierre Curie; Irene Joliot-Curie; Frederick Sanger; Linus Pauling; Rachel Carson; Lynn Margulis; Mary Anning; Gertrude Elion; Chien-Shiung Wu; Katherine Johnson; Mae Jemison; Flossie Wong-Staal; Hedy Lamarr; Ernst Mayr; Theodosius Dobzhansky; Motoo Kimura; Stephen Jay Gould; E. O. Wilson'
  , { names: true }),

q('Name a moon in our solar system',
  'The Moon/Moon/Luna; Titan; Europa; Io; Ganymede; Phobos',
  '',
  'Callisto; Enceladus; Triton; Charon; Deimos; Mimas',
  'Rhea; Iapetus; Dione; Tethys; Oberon; Titania; Umbriel; Ariel; Miranda; Nereid',
  'Hyperion; Phoebe; Amalthea; Himalia; Puck; Proteus; Larissa; Despina; Pandora; Prometheus; Janus; Epimetheus; Atlas',
  'Pan; Daphnis; Hydra; Nix; Kerberos; Styx; Elara; Pasiphae; Sinope; Lysithea; Carme; Ananke; Leda; Thebe; Metis; Adrastea; Helene; Telesto; Calypso; Pallene; Methone; Polydeuces; Anthe; Aegaeon; Cordelia; Ophelia; Bianca; Cressida; Desdemona; Juliet; Portia; Rosalind; Belinda; Caliban; Sycorax; Prospero; Setebos; Stephano; Trinculo; Ferdinand; Mab; Cupid; Perdita; Francisco; Margaret; Galatea; Thalassa; Naiad; Halimede; Sao; Laomedeia; Psamathe; Neso; Hippocamp'),

q('Name a constellation',
  'Orion; Ursa Major/Big Dipper; Ursa Minor/Little Dipper; Cassiopeia; Scorpius/Scorpio; Leo',
  '',
  'Taurus; Gemini; Cancer; Virgo; Libra; Sagittarius; Capricornus/Capricorn; Aquarius; Pisces; Aries; Cygnus; Draco; Pegasus; Lyra',
  'Andromeda; Perseus; Hercules; Canis Major; Canis Minor; Aquila; Bootes; Cepheus; Crux/Southern Cross; Centaurus; Auriga; Hydra; Cetus; Eridanus; Corona Borealis; Ophiuchus',
  'Lepus; Columba; Lupus; Ara; Vela; Carina; Puppis; Pyxis; Corvus; Crater; Sextans; Sagitta; Delphinus; Equuleus; Lynx; Camelopardalis; Monoceros; Triangulum; Vulpecula',
  'Antlia; Caelum; Fornax; Horologium; Mensa; Microscopium; Norma; Octans; Pictor; Reticulum; Sculptor; Telescopium; Volans; Apus; Chamaeleon; Dorado; Grus; Indus; Musca; Pavo; Phoenix; Tucana; Lacerta; Leo Minor; Coma Berenices; Canes Venatici; Circinus; Scutum; Corona Australis; Piscis Austrinus; Triangulum Australe; Hydrus'),

q('Name a bone in the human body',
  'Skull; Femur; Rib/Ribs; Spine; Pelvis; Tibia; Humerus; Clavicle/Collarbone',
  '',
  'Fibula; Radius; Ulna; Sternum; Scapula/Shoulder blade; Patella/Kneecap; Vertebra/Vertebrae; Jaw/Mandible; Coccyx/Tailbone; Sacrum',
  'Carpals; Metacarpals; Tarsals; Metatarsals; Phalanges; Talus; Calcaneus/Heel bone; Cranium; Maxilla; Hyoid; Stapes; Incus; Malleus; Scaphoid',
  'Lunate; Triquetrum; Pisiform; Trapezium; Trapezoid; Capitate; Hamate; Cuboid; Navicular; Cuneiform; Zygomatic; Nasal; Lacrimal; Palatine; Vomer; Sphenoid; Ethmoid; Occipital; Parietal; Temporal; Frontal',
  'Atlas; Axis; Ilium; Ischium; Pubis; Sesamoid; Xiphoid process; Manubrium; Acromion; Olecranon; Styloid process; Mastoid process; Mental protuberance'),

q('Name a gemstone',
  'Diamond; Ruby; Emerald; Sapphire; Opal; Amethyst; Topaz; Pearl',
  '',
  'Garnet; Turquoise; Jade; Aquamarine; Onyx; Peridot; Citrine; Moonstone; Lapis Lazuli/Lapis; Quartz; Obsidian; Agate; Tanzanite; Alexandrite',
  'Tourmaline; Spinel; Zircon; Tiger\'s Eye/Tigers Eye; Jasper; Malachite; Carnelian; Bloodstone; Morganite; Beryl; Amber; Coral; Jet; Rhodonite; Sunstone; Labradorite; Rose Quartz; Hematite; Pyrite; Smoky quartz',
  'Kunzite; Iolite; Sodalite; Chrysoberyl; Chrysoprase; Heliodor; Sphene; Diopside; Apatite; Fluorite; Larimar; Charoite; Sugilite; Kyanite; Rhodochrosite; Azurite; Aventurine; Chalcedony; Selenite; Sardonyx; Hiddenite; Andalusite; Prehnite; Tsavorite; Demantoid; Rhodolite',
  'Benitoite; Painite; Jeremejevite; Taaffeite; Grandidierite; Red beryl; Musgravite; Poudretteite; Hackmanite; Paraiba; Padparadscha; Ammolite; Serendibite; Kornerupine; Sinhalite; Tugtupite; Cuprite; Sphalerite; Axinite; Zoisite; Clinohumite; Sapphirine; Dumortierite; Eudialyte; Variscite'),

q('Name a type of cloud',
  'Cumulus; Cirrus; Stratus; Nimbus; Cumulonimbus',
  '',
  'Altocumulus; Altostratus; Cirrostratus; Cirrocumulus; Nimbostratus; Stratocumulus; Thunderhead',
  'Lenticular; Mammatus; Noctilucent; Contrail; Asperitas; Fractus; Pileus; Arcus/Shelf cloud; Roll cloud; Wall cloud; Funnel cloud; Fog; Anvil; Mackerel sky',
  'Kelvin-Helmholtz; Virga; Nacreous; Polar stratospheric; Pyrocumulus; Castellanus; Floccus; Undulatus; Fluctus; Cavum/Hole punch; Banner cloud; Morning glory; Mare\'s tails; Congestus; Humilis; Mediocris; Spissatus',
  'Volutus; Tuba; Cauda; Murus; Velum; Incus; Intortus; Vertebratus; Radiatus; Lacunosus; Duplicatus; Translucidus; Opacus; Perlucidus; Praecipitatio; Pannus; Flumen; Mamma; Fibratus; Uncinus; Calvus; Capillatus; Lenticularis'),

  );
})();
