(function () {
  const q = Trench.q;
  Trench.add('People',

q('Name a famous economist',
  'Adam Smith; John Maynard Keynes/Keynes; Milton Friedman; Karl Marx',
  '',
  'Paul Krugman; Ben Bernanke; Alan Greenspan; Janet Yellen; Jerome Powell; Friedrich Hayek/Hayek; Thomas Piketty; David Ricardo; Thomas Malthus; Joseph Stiglitz; Larry Summers; Paul Volcker; Joseph Schumpeter; Ludwig von Mises/Mises; John Kenneth Galbraith; Paul Samuelson; Gary Becker; Daniel Kahneman; Richard Thaler; Steven Levitt; Jeffrey Sachs; Robert Shiller; Eugene Fama; Ben Graham/Benjamin Graham; John Stuart Mill; Alfred Marshall; Thorstein Veblen; Mario Draghi; Christine Lagarde; Mark Carney; Ray Dalio',
  'Kenneth Arrow; John Nash; Amartya Sen; Robert Solow; Robert Lucas; Thomas Sargent; Edward Prescott; Finn Kydland; Robert Mundell; James Buchanan; Ronald Coase; Douglass North; Oliver Williamson; Elinor Ostrom; George Akerlof; Michael Spence; Angus Deaton; Esther Duflo; Abhijit Banerjee; Michael Kremer; Daron Acemoglu; Simon Johnson; James Robinson; Claudia Goldin; William Nordhaus; Paul Romer; Douglas Diamond; Philip Dybvig; Lars Peter Hansen; Jean Tirole; Alvin Roth; Lloyd Shapley; Christopher Sims; Peter Diamond; Dale Mortensen; Christopher Pissarides; Edmund Phelps; Robert Merton; Myron Scholes; Fischer Black; Harry Markowitz; William Sharpe; Merton Miller; Franco Modigliani; James Tobin; Hyman Minsky; Irving Fisher; Arthur Pigou; Vilfredo Pareto; Leon Walras; Carl Menger; Eugen von Bohm-Bawerk; Murray Rothbard; Henry George; Jean-Baptiste Say; Francois Quesnay; Anne Robert Jacques Turgot; Frederic Bastiat; Nassim Taleb; Tyler Cowen; Greg Mankiw; Raghuram Rajan; Nouriel Roubini; Kenneth Rogoff; Carmen Reinhart; Olivier Blanchard; Stanley Fischer; Mohamed El-Erian; Austan Goolsbee; Emily Oster; Raj Chetty; Susan Athey; Arthur Laffer; Art Laffer',
  'Richard Cantillon; William Petty; Thomas Mun; Johann Heinrich von Thunen; Antoine Augustin Cournot; Joseph Bertrand; Francis Ysidro Edgeworth; William Stanley Jevons; Knut Wicksell; Gustav Cassel; Bertil Ohlin; Eli Heckscher; Gunnar Myrdal; Ragnar Frisch; Jan Tinbergen; Wassily Leontief; Simon Kuznets; John Hicks; James Meade; Richard Stone; Trygve Haavelmo; Maurice Allais; Gerard Debreu; Tjalling Koopmans; Leonid Kantorovich; Herbert Simon; Theodore Schultz; Arthur Lewis; Piero Sraffa; Joan Robinson; Nicholas Kaldor; Michal Kalecki; Roy Harrod; Evsey Domar; Abba Lerner; Oskar Lange; Frank Knight; Jacob Viner; George Stigler; Aaron Director; Harold Hotelling; Ronald Fisher; Harold Demsetz; Armen Alchian; Gordon Tullock; Mancur Olson; Albert Hirschman; Kenneth Boulding; Nicholas Georgescu-Roegen; E.F. Schumacher; Herman Daly; Hernando de Soto; Muhammad Yunus; Jagdish Bhagwati; Dani Rodrik; Ha-Joon Chang; Mariana Mazzucato; Kate Raworth; Yanis Varoufakis; Stephanie Kelton; Warren Mosler; Pavlina Tcherneva; Gabriel Zucman; Emmanuel Saez; Branko Milanovic; Robert Gordon; Anat Admati; Hal Varian; Preston McAfee; Paul Milgrom; Robert Wilson; Roger Myerson; Eric Maskin; Leonid Hurwicz'.replace(/; Gary Becker; George/, '; George').replace(/; Ben Bernanke; Douglas/, '; Douglas'),
  'Ibn Khaldun; Nicole Oresme; Jean Bodin; Thomas Gresham; John Law; Bernard Mandeville; Dudley North; Ferdinando Galiani; Pietro Verri; Cesare Beccaria; Jeremy Bentham; Nassau Senior; Johann Gottlieb Fichte; Friedrich List; Adolph Wagner; Gustav von Schmoller; Werner Sombart; Max Weber; Rudolf Hilferding; Eduard Bernstein; Rosa Luxemburg; Nikolai Kondratiev; Yevgeny Preobrazhensky; Ludwig Lachmann; Israel Kirzner; Hans-Hermann Hoppe; Walter Eucken; Wilhelm Ropke; Alfred Muller-Armack; Ludwig Erhard; Raul Prebisch; Celso Furtado; Andre Gunder Frank; Samir Amin; Immanuel Wallerstein; Arghiri Emmanuel; Sukhamoy Chakravarty; Prasanta Mahalanobis; K.N. Raj; Manmohan Singh',
  { names: true }),

q('Name a philosopher',
  'Plato; Aristotle; Socrates; Confucius; Friedrich Nietzsche/Nietzsche; Immanuel Kant/Kant; Rene Descartes/Descartes',
  '',
  'John Locke/Locke; Thomas Hobbes/Hobbes; Jean-Jacques Rousseau/Rousseau; Voltaire; David Hume/Hume; Karl Marx/Marx; Soren Kierkegaard/Kierkegaard; Jean-Paul Sartre/Sartre; Albert Camus/Camus; Simone de Beauvoir; Niccolo Machiavelli/Machiavelli; Baruch Spinoza/Spinoza; Gottfried Leibniz/Leibniz; Georg Hegel/Hegel; Arthur Schopenhauer/Schopenhauer; John Stuart Mill; Jeremy Bentham; Thomas Aquinas/Aquinas; Augustine/Saint Augustine; Marcus Aurelius; Seneca; Epictetus; Epicurus; Diogenes; Pythagoras; Heraclitus; Lao Tzu/Laozi; Sun Tzu; Ludwig Wittgenstein/Wittgenstein; Bertrand Russell; Martin Heidegger/Heidegger; Michel Foucault/Foucault; Noam Chomsky; Ayn Rand; Francis Bacon; Thomas More; Adam Smith; Montesquieu; Blaise Pascal/Pascal; Henry David Thoreau/Thoreau; Ralph Waldo Emerson/Emerson; John Rawls; Peter Singer; Slavoj Zizek; Alan Watts',
  'Parmenides; Zeno of Elea/Zeno; Democritus; Anaximander; Thales; Empedocles; Anaxagoras; Protagoras; Xenophon; Plotinus; Boethius; Avicenna/Ibn Sina; Averroes/Ibn Rushd; Al-Farabi; Al-Ghazali; Maimonides; Anselm; Peter Abelard; Duns Scotus; William of Ockham/Ockham; Erasmus; Michel de Montaigne/Montaigne; Giordano Bruno; Hugo Grotius; George Berkeley/Berkeley; Thomas Reid; Edmund Burke; Mary Wollstonecraft; Johann Fichte/Fichte; Friedrich Schelling/Schelling; Ludwig Feuerbach; Auguste Comte; Herbert Spencer; Charles Sanders Peirce; William James; John Dewey; George Santayana; Edmund Husserl; Max Scheler; Henri Bergson; Alfred North Whitehead; G.E. Moore; Gottlob Frege; Rudolf Carnap; Karl Popper; A.J. Ayer; Gilbert Ryle; J.L. Austin; W.V.O. Quine/Quine; Hannah Arendt; Simone Weil; Maurice Merleau-Ponty; Emmanuel Levinas; Jacques Derrida/Derrida; Gilles Deleuze; Jean Baudrillard; Jean-Francois Lyotard; Roland Barthes; Theodor Adorno; Max Horkheimer; Herbert Marcuse; Walter Benjamin; Jurgen Habermas/Habermas; Antonio Gramsci; Louis Althusser; Thomas Kuhn; Paul Feyerabend; Saul Kripke; David Lewis; Robert Nozick; Daniel Dennett; Thomas Nagel; Martha Nussbaum; Judith Butler; Richard Rorty; Hilary Putnam; Donald Davidson; Alasdair MacIntyre; Charles Taylor; Bernard Williams; Derek Parfit; Philippa Foot; Elizabeth Anscombe; Iris Murdoch; Zhuangzi; Mencius; Mozi; Xunzi; Han Feizi; Nagarjuna; Adi Shankara; Siddhartha Gautama/Buddha; Kautilya/Chanakya',
  'Anaximenes; Xenophanes; Leucippus; Gorgias; Antisthenes; Aristippus; Pyrrho; Zeno of Citium; Chrysippus; Cleanthes; Carneades; Sextus Empiricus; Lucretius; Cicero; Philo of Alexandria; Porphyry; Iamblichus; Proclus; Hypatia; Pseudo-Dionysius; John Scotus Eriugena; Al-Kindi; Ibn Arabi; Suhrawardi; Mulla Sadra; Ibn Taymiyyah; Ibn Khaldun; Bonaventure; Albertus Magnus; Roger Bacon; Meister Eckhart; Nicholas of Cusa; Marsilio Ficino; Pico della Mirandola; Pietro Pomponazzi; Francisco Suarez; Pierre Gassendi; Nicolas Malebranche; Ralph Cudworth; Anne Conway; Margaret Cavendish; Pierre Bayle; Bernard de Fontenelle; Giambattista Vico; Francis Hutcheson; Joseph Butler; Lord Shaftesbury; Julien Offray de La Mettrie; Denis Diderot; Jean le Rond d\'Alembert; Condorcet; Claude Adrien Helvetius; Baron d\'Holbach; Johann Gottfried Herder; Friedrich Jacobi; Moses Mendelssohn; Johann Georg Hamann; Friedrich Schleiermacher; Wilhelm Dilthey; Hermann Lotze; Franz Brentano; Alexius Meinong; Ernst Mach; Moritz Schlick; Otto Neurath; Hans Reichenbach; Carl Hempel; Nelson Goodman; Wilfrid Sellars; Peter Strawson; Michael Dummett; Jaegwon Kim; Ruth Barcan Marcus; G.E.M. Anscombe; Mary Midgley; Harry Frankfurt; Jerry Fodor; Hubert Dreyfus; John Searle; Patricia Churchland; Paul Churchland; Ned Block; David Chalmers; Nick Bostrom; Kwame Anthony Appiah',
  { names: true }),

q('Name a US Supreme Court justice, past or present',
  'Ruth Bader Ginsburg/RBG/Ginsburg; Clarence Thomas; John Roberts; Sonia Sotomayor; Brett Kavanaugh; Amy Coney Barrett',
  '',
  'Samuel Alito; Elena Kagan; Neil Gorsuch; Ketanji Brown Jackson; Antonin Scalia/Scalia; Thurgood Marshall; Sandra Day O\'Connor; Anthony Kennedy; Stephen Breyer; John Marshall; Earl Warren; Oliver Wendell Holmes; William Rehnquist; David Souter; John Paul Stevens',
  'Harry Blackmun; William Brennan; Lewis Powell; Byron White; Warren Burger; Potter Stewart; Hugo Black; William O. Douglas; Felix Frankfurter; Louis Brandeis; Robert Jackson; Benjamin Cardozo; Charles Evans Hughes; William Howard Taft; Roger Taney; Joseph Story; John Jay; Abe Fortas; Arthur Goldberg; Tom Clark; John Marshall Harlan; Stanley Reed; Harlan Fiske Stone; Fred Vinson; Owen Roberts',
  'Salmon P. Chase; Morrison Waite; Melville Fuller; Edward Douglass White; Bushrod Washington; William Johnson; Samuel Chase; James Wilson; John Rutledge; Oliver Ellsworth; William Cushing; John Blair; James Iredell; Thomas Johnson; William Paterson; Alfred Moore; Henry Brockholst Livingston; Thomas Todd; Gabriel Duvall; Smith Thompson; Robert Trimble; John McLean; Henry Baldwin; James Wayne; Philip Barbour; John Catron; John McKinley; Peter Daniel; Samuel Nelson; Levi Woodbury; Robert Grier; Benjamin Curtis; John Campbell; Nathan Clifford; Noah Swayne; Samuel Miller; David Davis; Stephen Field; William Strong; Joseph Bradley; Ward Hunt; Stanley Matthews; Horace Gray; Samuel Blatchford; Lucius Lamar; David Brewer; Henry Billings Brown; George Shiras; Howell Jackson; Rufus Peckham; Joseph McKenna; William Day; William Moody; Horace Lurton; Joseph Lamar; Mahlon Pitney; James McReynolds; John Clarke; George Sutherland; Pierce Butler; Edward Sanford; Wiley Rutledge; Frank Murphy; James Byrnes; Harold Burton; Sherman Minton; Charles Whittaker',
  '',
  { names: true }),

q('Name a US vice president',
  'Kamala Harris; Mike Pence; Joe Biden; Dick Cheney; Al Gore; JD Vance/J.D. Vance',
  '',
  'Dan Quayle; George H. W. Bush; Walter Mondale; Nelson Rockefeller; Gerald Ford; Spiro Agnew; Hubert Humphrey; Lyndon B. Johnson/LBJ; Richard Nixon; Harry Truman; John Adams; Thomas Jefferson; Aaron Burr; Theodore Roosevelt',
  'Alben Barkley; Henry Wallace; John Nance Garner; Charles Curtis; Charles Dawes; Calvin Coolidge; Thomas Marshall; James Sherman; Charles Fairbanks; Garret Hobart; Adlai Stevenson I/Adlai Stevenson; Levi Morton; Thomas Hendricks; Chester Arthur; William Wheeler; Henry Wilson; Schuyler Colfax; Andrew Johnson; Hannibal Hamlin; John Breckinridge; William King; Millard Fillmore; George Dallas; John Tyler; Richard Mentor Johnson; Martin Van Buren; John C. Calhoun; Daniel Tompkins; Elbridge Gerry; George Clinton',
  '',
  '',
  { names: true }),

q('Name a Founding Father',
  'George Washington; Benjamin Franklin; Thomas Jefferson; Alexander Hamilton; John Adams; James Madison',
  '',
  'John Hancock; John Jay; Samuel Adams/Sam Adams; Patrick Henry; Paul Revere; James Monroe; Thomas Paine; Aaron Burr; Gouverneur Morris; John Marshall; George Mason; Robert Morris; Benjamin Rush; Roger Sherman; John Dickinson; Charles Carroll; Richard Henry Lee',
  'Elbridge Gerry; Rufus King; Charles Pinckney; Charles Cotesworth Pinckney; Edmund Randolph; Oliver Ellsworth; William Paterson; James Wilson; John Rutledge; Edward Rutledge; Caesar Rodney; Thomas McKean; George Read; Button Gwinnett; Lyman Hall; George Walton; Stephen Hopkins; William Ellery; Josiah Bartlett; William Whipple; Matthew Thornton; Robert Treat Paine; Francis Hopkinson; John Witherspoon; Richard Stockton; Abraham Clark; John Hart; Philip Livingston; Lewis Morris; Francis Lewis; William Floyd; Carter Braxton; Benjamin Harrison V; Thomas Nelson Jr.; Francis Lightfoot Lee; George Wythe; Thomas Heyward Jr.; Arthur Middleton; Thomas Lynch Jr.; Joseph Hewes; William Hooper; John Penn; Samuel Chase; William Paca; Thomas Stone; Robert R. Livingston; Henry Knox; Nathanael Greene; Marquis de Lafayette/Lafayette; John Langdon; Nicholas Gilman; William Samuel Johnson; Jared Ingersoll; Thomas Mifflin; George Clymer; Thomas FitzSimons; Daniel of St. Thomas Jenifer; Daniel Carroll; James McHenry; John Blair; William Blount; Richard Dobbs Spaight; Hugh Williamson; Pierce Butler; Abraham Baldwin; William Few; David Brearley; Jonathan Dayton; William Livingston; Gunning Bedford Jr.; Jacob Broom; Richard Bassett; Mercy Otis Warren; Abigail Adams; Haym Salomon; Crispus Attucks; Ethan Allen; Nathan Hale',
  '',
  '',
  { names: true }),

q('Name a famous author',
  'William Shakespeare/Shakespeare; Mark Twain; Ernest Hemingway/Hemingway; Stephen King; J.K. Rowling/JK Rowling; Jane Austen; Charles Dickens',
  '',
  'F. Scott Fitzgerald/Fitzgerald; George Orwell/Orwell; Edgar Allan Poe/Poe; Leo Tolstoy/Tolstoy; Fyodor Dostoevsky/Dostoevsky; J.R.R. Tolkien/Tolkien; C.S. Lewis; Harper Lee; John Steinbeck/Steinbeck; William Faulkner/Faulkner; Virginia Woolf; Toni Morrison; Maya Angelou; Dr. Seuss; Roald Dahl; Agatha Christie; Arthur Conan Doyle; James Joyce; Oscar Wilde; Herman Melville; Nathaniel Hawthorne; Kurt Vonnegut/Vonnegut; J.D. Salinger/Salinger; Ray Bradbury; Cormac McCarthy; John Grisham; Dan Brown; James Patterson; Danielle Steel; George R.R. Martin; Suzanne Collins; Rick Riordan; Judy Blume; Beverly Cleary; Mary Shelley; Bram Stoker; Emily Bronte; Charlotte Bronte; Louisa May Alcott; Jack London; Homer; Dante; Miguel de Cervantes/Cervantes; Victor Hugo; Alexandre Dumas; Jules Verne; H.G. Wells; Aldous Huxley; Ayn Rand; Sylvia Plath; Walt Whitman; Emily Dickinson; Robert Frost; Langston Hughes; Gabriel Garcia Marquez; Haruki Murakami; Franz Kafka/Kafka; Anton Chekhov; Sally Rooney; Colleen Hoover; Malcolm Gladwell; Michael Lewis; John Green; Khaled Hosseini; Margaret Atwood; Salman Rushdie; Ian McEwan; Kazuo Ishiguro; Chimamanda Ngozi Adichie; Zadie Smith; Jonathan Franzen; David Foster Wallace; Don DeLillo; Philip Roth; Thomas Pynchon; Joan Didion; Truman Capote; Tennessee Williams; Arthur Miller; Hunter S. Thompson; Jack Kerouac; Allen Ginsberg; Neil Gaiman; Terry Pratchett; Douglas Adams; Isaac Asimov; Frank Herbert; Philip K. Dick; Ursula K. Le Guin; Octavia Butler; Tom Clancy; Michael Crichton; Dean Koontz; Anne Rice; Nicholas Sparks; Jodi Picoult; Gillian Flynn; Paula Hawkins; Liane Moriarty; Brandon Sanderson; Andy Weir',
  'Henry James; Edith Wharton; Willa Cather; Sinclair Lewis; Theodore Dreiser; Upton Sinclair; Zora Neale Hurston; Richard Wright; Ralph Ellison; James Baldwin; Flannery O\'Connor; Eudora Welty; Carson McCullers; Saul Bellow; John Updike; Norman Mailer; Gore Vidal; Joseph Heller; Ken Kesey; William S. Burroughs; E.L. Doctorow; Raymond Carver; John Cheever; Richard Yates; Wallace Stegner; Larry McMurtry; Annie Proulx; Marilynne Robinson; Jhumpa Lahiri; Michael Chabon; Jonathan Safran Foer; Dave Eggers; George Saunders; Colson Whitehead; Jesmyn Ward; Donna Tartt; Bret Easton Ellis; Jay McInerney; Tom Wolfe; Thomas Wolfe; Sherwood Anderson; John Dos Passos; Dashiell Hammett; Raymond Chandler; James M. Cain; Patricia Highsmith; Shirley Jackson; Ira Levin; Elmore Leonard; Walter Mosley; Thomas Hardy; George Eliot; Anthony Trollope; William Makepeace Thackeray; Elizabeth Gaskell; Wilkie Collins; Lewis Carroll; Rudyard Kipling; Joseph Conrad; E.M. Forster; D.H. Lawrence; Evelyn Waugh; Graham Greene; P.G. Wodehouse; Anthony Burgess; William Golding; Iris Murdoch; Doris Lessing; Muriel Spark; Martin Amis; Julian Barnes; Hilary Mantel; Ali Smith; Penelope Fitzgerald; Jean Rhys; Daphne du Maurier; Nancy Mitford; Honore de Balzac; Gustave Flaubert; Emile Zola; Marcel Proust; Stendhal; Guy de Maupassant; Andre Gide; Colette; Marguerite Duras; Albert Camus; Samuel Beckett; Thomas Mann; Hermann Hesse; Gunter Grass; W.G. Sebald; Goethe; Friedrich Schiller; Nikolai Gogol; Ivan Turgenev; Alexander Pushkin; Mikhail Bulgakov; Vladimir Nabokov; Aleksandr Solzhenitsyn; Boris Pasternak; Jorge Luis Borges; Julio Cortazar; Mario Vargas Llosa; Isabel Allende; Pablo Neruda; Roberto Bolano; Carlos Fuentes; Octavio Paz; Italo Calvino; Umberto Eco; Primo Levi; Elena Ferrante; Natalia Ginzburg; Yukio Mishima; Yasunari Kawabata; Kenzaburo Oe; Chinua Achebe; Ngugi wa Thiong\'o; Wole Soyinka; Naguib Mahfouz; Orhan Pamuk; Rabindranath Tagore; R.K. Narayan; Arundhati Roy; Vikram Seth; V.S. Naipaul; Derek Walcott; Jamaica Kincaid; Alice Munro; Robertson Davies; Michael Ondaatje; Yann Martel; Patrick White; Peter Carey; Tim Winton; Janet Frame; Katherine Mansfield',
  'Laurence Sterne; Samuel Richardson; Henry Fielding; Tobias Smollett; Daniel Defoe; Jonathan Swift; Fanny Burney; Ann Radcliffe; Matthew Lewis; Horace Walpole; Maria Edgeworth; Walter Scott; James Hogg; Thomas De Quincey; Charles Lamb; William Hazlitt; Thomas Love Peacock; George Meredith; George Gissing; Arnold Bennett; John Galsworthy; Ford Madox Ford; Ivy Compton-Burnett; Elizabeth Bowen; Henry Green; Anthony Powell; Barbara Pym; Angus Wilson; B.S. Johnson; Ann Quin; Christine Brooke-Rose; Flann O\'Brien; Brian Moore; John McGahern; Edna O\'Brien; William Trevor; Colm Toibin; Anne Enright; Sebastian Barry; Claire Keegan; Charles Brockden Brown; James Fenimore Cooper; Washington Irving; William Dean Howells; Stephen Crane; Frank Norris; Kate Chopin; Sarah Orne Jewett; Charlotte Perkins Gilman; Ambrose Bierce; O. Henry; Ring Lardner; Nathanael West; James T. Farrell; Henry Roth; Djuna Barnes; Jean Toomer; Nella Larsen; Dawn Powell; William Gaddis; John Barth; William Gass; Donald Barthelme; Robert Coover; Stanley Elkin; John Hawkes; Paula Fox; Grace Paley; Tillie Olsen; Evan S. Connell; John Williams; Richard Powers; William T. Vollmann; Denis Johnson; Lydia Davis; Amy Hempel; Barry Hannah; Harry Crews; Charles Portis; Walker Percy; Peter Taylor; Reynolds Price'),

  );
})();
